CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE EXTENSION IF NOT EXISTS citext;

  

CREATE SCHEMA IF NOT EXISTS app;

CREATE SCHEMA IF NOT EXISTS competition;

CREATE SCHEMA IF NOT EXISTS prayer;

CREATE SCHEMA IF NOT EXISTS platform;