INSERT INTO competition.point_rules (
    code,
    activity_code,
    name,
    description,
    points,
    daily_limit,
    weekly_limit,
    effective_from,
    effective_until,
    is_active
)
VALUES
    (
        'POINTS_SCRIPTURE_READ',
        'SCRIPTURE_READ',
        'Scripture Reading Points',
        'Awards points when the user reads the daily Scripture, Gospel, or assigned Bible passage.',
        50,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_PRAYER_COMPLETED',
        'PRAYER_COMPLETED',
        'Prayer Session Points',
        'Awards points when the user completes a focused prayer session.',
        40,
        3,
        21,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_ROSARY_COMPLETED',
        'ROSARY_COMPLETED',
        'Rosary Points',
        'Awards points when the user completes a Rosary prayer activity. Challenge rules may define one decade, full Rosary, or multiple Rosaries.',
        75,
        2,
        14,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_EXAMEN_COMPLETED',
        'EXAMEN_COMPLETED',
        'Evening Examen Points',
        'Awards points when the user completes an evening examen or examination of conscience.',
        40,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_PHONE_FAST_COMPLETED',
        'PHONE_FAST_COMPLETED',
        'Phone Fast Points',
        'Awards points when the user completes a phone or social media fast to fight distraction and build self-control.',
        60,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_ROOM_CLEANED',
        'ROOM_CLEANED',
        'Room Cleaned Points',
        'Awards points when the user cleans their room, desk, or workspace as an act of order and discipline.',
        35,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_EXERCISE_COMPLETED',
        'EXERCISE_COMPLETED',
        'Exercise Points',
        'Awards points when the user completes a physical exercise activity.',
        60,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_FRIEND_CONTACTED',
        'FRIEND_CONTACTED',
        'Friend Contacted Points',
        'Awards points when the user contacts a trusted friend, family member, mentor, or accountability partner instead of isolating.',
        40,
        2,
        14,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_ACT_OF_MERCY_COMPLETED',
        'ACT_OF_MERCY_COMPLETED',
        'Act of Mercy Points',
        'Awards points when the user completes a concrete act of charity, mercy, or service for another person.',
        70,
        3,
        21,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_ENCOURAGEMENT_SENT',
        'ENCOURAGEMENT_SENT',
        'Encouragement Sent Points',
        'Awards points when the user sends a preset encouragement icon or message to another user.',
        20,
        5,
        35,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_DEMON_DEFENSE_COMPLETED',
        'DEMON_DEFENSE_COMPLETED',
        'Demon Defense Points',
        'Awards points when the user completes a real-world defense action against an active demon battle.',
        90,
        3,
        21,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_DEMON_DEFEATED',
        'DEMON_DEFEATED',
        'Demon Defeated Points',
        'Awards points when the user defeats an active demon by completing enough real-world defense actions.',
        150,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_CONFESSION_PREP_COMPLETED',
        'CONFESSION_PREP_COMPLETED',
        'Confession Preparation Points',
        'Awards points when the user completes an examination of conscience and prepares honestly for Confession. This does not replace the sacrament.',
        100,
        1,
        1,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_MASS_ATTENDED',
        'MASS_ATTENDED',
        'Mass Attendance Points',
        'Awards points when the user attends Mass and records the activity for spiritual habit tracking.',
        150,
        1,
        7,
        NOW(),
        NULL,
        TRUE
    ),
    (
        'POINTS_CHALLENGE_COMPLETED',
        'CHALLENGE_COMPLETED',
        'Challenge Completed Points',
        'Awards points when the user completes a general challenge, often used for special recovery or reset missions.',
        50,
        5,
        35,
        NOW(),
        NULL,
        TRUE
    )
ON CONFLICT (code) DO UPDATE
SET
    activity_code = EXCLUDED.activity_code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    points = EXCLUDED.points,
    daily_limit = EXCLUDED.daily_limit,
    weekly_limit = EXCLUDED.weekly_limit,
    effective_from = EXCLUDED.effective_from,
    effective_until = EXCLUDED.effective_until,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();