INSERT INTO competition.challenge_definitions (
    code,
    title,
    description,
    challenge_type,
    activity_code,
    target_quantity,
    xp_reward,
    badge_reward_id,
    difficulty,
    assignment_weight,
    rules,
    icon_url,
    starts_at,
    ends_at,
    is_active
)
VALUES
    (
        'DAILY_SCRIPTURE_READER',
        'Read Today''s Scripture',
        'Read the daily Scripture passage and reflect on one thing God is asking of you today.',
        'daily',
        'SCRIPTURE_READ',
        1,
        50,
        NULL,
        'easy',
        100,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "requiresReflection": false,
            "virtues": ["wisdom", "faith"],
            "recommendedMinutes": 5
        }'::jsonb,
        '/icons/challenges/scripture.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_PRAYER_5_MIN',
        'Pray for 5 Minutes',
        'Spend five focused minutes in prayer without distractions.',
        'daily',
        'PRAYER_COMPLETED',
        1,
        40,
        NULL,
        'easy',
        100,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "minimumMinutes": 5,
            "virtues": ["faith", "perseverance"],
            "phoneAwayRecommended": true
        }'::jsonb,
        '/icons/challenges/prayer.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_ONE_DECADE_ROSARY',
        'Pray One Decade',
        'Pray one decade of the Rosary with attention and reverence.',
        'daily',
        'ROSARY_COMPLETED',
        1,
        60,
        NULL,
        'easy',
        90,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "minimumDecades": 1,
            "virtues": ["faith", "purity", "perseverance"],
            "fullRosaryRequired": false
        }'::jsonb,
        '/icons/challenges/rosary-decade.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_FULL_ROSARY',
        'Pray a Full Rosary',
        'Complete a full Rosary and offer it for someone who needs prayer.',
        'daily',
        'ROSARY_COMPLETED',
        1,
        120,
        NULL,
        'normal',
        45,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "minimumDecades": 5,
            "virtues": ["faith", "discipline", "charity"],
            "offerForSomeone": true
        }'::jsonb,
        '/icons/challenges/rosary-full.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_EXAMEN',
        'Evening Examen',
        'Review your day honestly: where you followed God, where you failed, and what you must correct tomorrow.',
        'daily',
        'EXAMEN_COMPLETED',
        1,
        50,
        NULL,
        'easy',
        85,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "recommendedTimeOfDay": "evening",
            "virtues": ["wisdom", "humility", "perseverance"],
            "reflectionPrompts": [
                "What am I grateful for?",
                "Where did I fail?",
                "What will I correct tomorrow?"
            ]
        }'::jsonb,
        '/icons/challenges/examen.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_PHONE_AWAY_BEDTIME',
        'Phone Away Before Bed',
        'Put your phone at least six feet away before bedtime to protect your mind and sleep.',
        'daily',
        'PHONE_FAST_COMPLETED',
        1,
        50,
        NULL,
        'easy',
        95,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "minimumDistanceFeet": 6,
            "recommendedTimeOfDay": "night",
            "counters": ["late_night_scrolling", "lust", "distraction"],
            "virtues": ["temperance", "discipline", "purity"]
        }'::jsonb,
        '/icons/challenges/phone-away.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_CLEAN_YOUR_SPACE',
        'Clean Your Room',
        'Clean your room, desk, or workspace for at least ten minutes.',
        'daily',
        'ROOM_CLEANED',
        1,
        40,
        NULL,
        'easy',
        90,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "minimumMinutes": 10,
            "counters": ["distraction", "sloth", "chaos"],
            "virtues": ["order", "discipline"]
        }'::jsonb,
        '/icons/challenges/clean-room.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_EXERCISE_20_MIN',
        'Exercise for 20 Minutes',
        'Move your body for twenty minutes to fight laziness, boredom, and restlessness.',
        'daily',
        'EXERCISE_COMPLETED',
        1,
        70,
        NULL,
        'normal',
        80,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "minimumMinutes": 20,
            "counters": ["boredom", "sloth", "temptation"],
            "virtues": ["discipline", "courage", "temperance"]
        }'::jsonb,
        '/icons/challenges/exercise.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_CALL_SOMEONE',
        'Call Someone',
        'Call or message a trusted person instead of isolating yourself.',
        'daily',
        'FRIEND_CONTACTED',
        1,
        50,
        NULL,
        'easy',
        75,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "counters": ["loneliness", "isolation", "despair"],
            "virtues": ["charity", "brotherhood", "hope"],
            "allowTextMessage": true
        }'::jsonb,
        '/icons/challenges/call-friend.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_ACT_OF_MERCY',
        'Do One Act of Mercy',
        'Do one concrete act of love for another person without expecting praise.',
        'daily',
        'ACT_OF_MERCY_COMPLETED',
        1,
        80,
        NULL,
        'normal',
        70,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "virtues": ["charity", "humility", "service"],
            "mustBeConcreteAction": true,
            "examples": [
                "Help someone at home",
                "Encourage someone",
                "Serve without being noticed",
                "Give time to someone in need"
            ]
        }'::jsonb,
        '/icons/challenges/mercy.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_ENCOURAGE_FRIEND',
        'Encourage a Friend',
        'Send a preset encouragement icon to a friend who earned a badge or achievement.',
        'daily',
        'ENCOURAGEMENT_SENT',
        1,
        30,
        NULL,
        'easy',
        60,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 3,
            "requiresFriendAchievementContext": true,
            "freeTextAllowed": false,
            "virtues": ["charity", "community"]
        }'::jsonb,
        '/icons/challenges/encouragement.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_DEMON_DEFENSE',
        'Complete a Demon Defense',
        'Choose one active demon attack and complete the matching real-world defense.',
        'daily',
        'DEMON_DEFENSE_COMPLETED',
        1,
        90,
        NULL,
        'normal',
        100,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 3,
            "requiresActiveDemonBattle": true,
            "serverCalculatesDamage": true,
            "virtues": ["discipline", "courage", "temperance"]
        }'::jsonb,
        '/icons/challenges/demon-defense.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'DAILY_DEFEAT_DEMON',
        'Defeat One Demon',
        'Defeat one active demon by completing enough real-world defenses.',
        'daily',
        'DEMON_DEFEATED',
        1,
        150,
        NULL,
        'hard',
        35,
        '{
            "frequency": "daily",
            "maxCompletionsPerDay": 1,
            "requiresActiveDemonBattle": true,
            "rewardOnlyOnBattleVictory": true,
            "virtues": ["perseverance", "courage", "discipline"]
        }'::jsonb,
        '/icons/challenges/defeat-demon.png',
        NULL,
        NULL,
        TRUE
    ),

    -- Weekly challenges

    (
        'WEEKLY_SCRIPTURE_5_DAYS',
        'Read Scripture 5 Days',
        'Read Scripture on five different days this week.',
        'weekly',
        'SCRIPTURE_READ',
        5,
        250,
        NULL,
        'normal',
        85,
        '{
            "frequency": "weekly",
            "requiresDistinctDays": true,
            "minimumDistinctDays": 5,
            "virtues": ["wisdom", "faith", "discipline"]
        }'::jsonb,
        '/icons/challenges/scripture-week.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'WEEKLY_ROSARY_3_TIMES',
        'Pray the Rosary 3 Times',
        'Pray the Rosary three times this week.',
        'weekly',
        'ROSARY_COMPLETED',
        3,
        300,
        NULL,
        'normal',
        70,
        '{
            "frequency": "weekly",
            "requiresDistinctDays": false,
            "targetUnit": "rosary",
            "virtues": ["faith", "discipline", "perseverance"]
        }'::jsonb,
        '/icons/challenges/rosary-week.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'WEEKLY_EXERCISE_4_DAYS',
        'Exercise 4 Days',
        'Exercise on four different days this week.',
        'weekly',
        'EXERCISE_COMPLETED',
        4,
        250,
        NULL,
        'normal',
        65,
        '{
            "frequency": "weekly",
            "requiresDistinctDays": true,
            "minimumMinutesPerSession": 20,
            "virtues": ["discipline", "temperance"]
        }'::jsonb,
        '/icons/challenges/exercise-week.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'WEEKLY_ACTS_OF_MERCY_5',
        'Five Acts of Mercy',
        'Complete five concrete acts of mercy this week.',
        'weekly',
        'ACT_OF_MERCY_COMPLETED',
        5,
        350,
        NULL,
        'hard',
        55,
        '{
            "frequency": "weekly",
            "targetUnit": "acts",
            "virtues": ["charity", "humility", "service"],
            "encourageVariety": true
        }'::jsonb,
        '/icons/challenges/mercy-week.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'WEEKLY_DEMON_DEFENSES_7',
        'Seven Demon Defenses',
        'Complete seven demon defenses this week.',
        'weekly',
        'DEMON_DEFENSE_COMPLETED',
        7,
        400,
        NULL,
        'hard',
        60,
        '{
            "frequency": "weekly",
            "requiresActiveDemonBattle": true,
            "targetUnit": "defenses",
            "virtues": ["courage", "discipline", "perseverance"]
        }'::jsonb,
        '/icons/challenges/demon-defense-week.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'WEEKLY_CONFESSION_PREP',
        'Prepare for Confession',
        'Complete an examination of conscience and prepare honestly for Confession.',
        'weekly',
        'CONFESSION_PREP_COMPLETED',
        1,
        200,
        NULL,
        'normal',
        40,
        '{
            "frequency": "weekly",
            "maxCompletionsPerWeek": 1,
            "doesNotReplaceSacrament": true,
            "virtues": ["humility", "wisdom", "repentance"]
        }'::jsonb,
        '/icons/challenges/confession-prep.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'WEEKLY_SUNDAY_MASS',
        'Attend Sunday Mass',
        'Attend Sunday Mass and keep the Lord''s Day holy.',
        'weekly',
        'MASS_ATTENDED',
        1,
        250,
        NULL,
        'normal',
        100,
        '{
            "frequency": "weekly",
            "recommendedDay": "sunday",
            "doesNotReplaceObligation": true,
            "virtues": ["faith", "worship", "gratitude"]
        }'::jsonb,
        '/icons/challenges/sunday-mass.png',
        NULL,
        NULL,
        TRUE
    ),

    -- Special challenges

    (
        'SPECIAL_24_HOUR_SOCIAL_FAST',
        '24-Hour Social Media Fast',
        'Stay away from social media for twenty-four hours and use the time for prayer, work, family, or service.',
        'special',
        'PHONE_FAST_COMPLETED',
        1,
        300,
        NULL,
        'hard',
        30,
        '{
            "durationHours": 24,
            "counters": ["distraction", "comparison", "lust", "envy"],
            "virtues": ["temperance", "discipline", "purity"],
            "allowedUses": ["work_required", "family_required"],
            "requiresStartAndEndCheckIn": true
        }'::jsonb,
        '/icons/challenges/social-fast.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'SPECIAL_BATTLE_RESET',
        'Return to the Battle',
        'After a missed day or failed challenge, complete one small mission and return without giving up.',
        'special',
        'CHALLENGE_COMPLETED',
        1,
        100,
        NULL,
        'easy',
        50,
        '{
            "trigger": "after_missed_day",
            "purpose": "recovery",
            "doesNotRestoreStreakAutomatically": true,
            "virtues": ["hope", "perseverance", "humility"]
        }'::jsonb,
        '/icons/challenges/return-battle.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'SPECIAL_ARENA_CLEAR',
        'Clear the Arena',
        'Defeat all active demons in your arena.',
        'special',
        'DEMON_DEFEATED',
        7,
        1000,
        NULL,
        'heroic',
        10,
        '{
            "requiresArena": true,
            "requiresAllActiveDemonsDefeated": true,
            "maxActiveDemons": 7,
            "unlocksGuardianCheck": true,
            "virtues": ["courage", "perseverance", "discipline", "faith"]
        }'::jsonb,
        '/icons/challenges/clear-arena.png',
        NULL,
        NULL,
        TRUE
    ),

    -- Seasonal challenges

    (
        'SEASONAL_ADVENT_PRAYER',
        'Advent Prayer Mission',
        'During Advent, complete daily prayer and prepare your heart for Christ.',
        'seasonal',
        'PRAYER_COMPLETED',
        7,
        500,
        NULL,
        'normal',
        20,
        '{
            "season": "advent",
            "requiresDistinctDays": true,
            "minimumMinutesPerDay": 5,
            "virtues": ["hope", "faith", "patience"]
        }'::jsonb,
        '/icons/challenges/advent.png',
        NULL,
        NULL,
        TRUE
    ),
    (
        'SEASONAL_LENTEN_DISCIPLINE',
        'Lenten Discipline',
        'During Lent, complete acts of prayer, fasting, and mercy.',
        'seasonal',
        'ACT_OF_MERCY_COMPLETED',
        10,
        800,
        NULL,
        'hard',
        20,
        '{
            "season": "lent",
            "theme": "prayer_fasting_almsgiving",
            "requiresDistinctDays": true,
            "virtues": ["temperance", "charity", "repentance"]
        }'::jsonb,
        '/icons/challenges/lent.png',
        NULL,
        NULL,
        TRUE
    )
ON CONFLICT (code) DO UPDATE
SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    challenge_type = EXCLUDED.challenge_type,
    activity_code = EXCLUDED.activity_code,
    target_quantity = EXCLUDED.target_quantity,
    xp_reward = EXCLUDED.xp_reward,
    badge_reward_id = EXCLUDED.badge_reward_id,
    difficulty = EXCLUDED.difficulty,
    assignment_weight = EXCLUDED.assignment_weight,
    rules = EXCLUDED.rules,
    icon_url = EXCLUDED.icon_url,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();