-- Populate every currently assigned ISO 3166-1 alpha-2 code. Existing
-- coordinates are preserved; newly added catalog rows intentionally leave
-- coordinates null until authoritative values are supplied separately.
insert into app.countries (code, name, is_active)
values
  ('AD', 'Andorra', true),
  ('AE', 'United Arab Emirates', true),
  ('AF', 'Afghanistan', true),
  ('AG', 'Antigua & Barbuda', true),
  ('AI', 'Anguilla', true),
  ('AL', 'Albania', true),
  ('AM', 'Armenia', true),
  ('AO', 'Angola', true),
  ('AQ', 'Antarctica', true),
  ('AR', 'Argentina', true),
  ('AS', 'American Samoa', true),
  ('AT', 'Austria', true),
  ('AU', 'Australia', true),
  ('AW', 'Aruba', true),
  ('AX', 'Åland Islands', true),
  ('AZ', 'Azerbaijan', true),
  ('BA', 'Bosnia & Herzegovina', true),
  ('BB', 'Barbados', true),
  ('BD', 'Bangladesh', true),
  ('BE', 'Belgium', true),
  ('BF', 'Burkina Faso', true),
  ('BG', 'Bulgaria', true),
  ('BH', 'Bahrain', true),
  ('BI', 'Burundi', true),
  ('BJ', 'Benin', true),
  ('BL', 'St. Barthélemy', true),
  ('BM', 'Bermuda', true),
  ('BN', 'Brunei', true),
  ('BO', 'Bolivia', true),
  ('BQ', 'Caribbean Netherlands', true),
  ('BR', 'Brazil', true),
  ('BS', 'Bahamas', true),
  ('BT', 'Bhutan', true),
  ('BV', 'Bouvet Island', true),
  ('BW', 'Botswana', true),
  ('BY', 'Belarus', true),
  ('BZ', 'Belize', true),
  ('CA', 'Canada', true),
  ('CC', 'Cocos (Keeling) Islands', true),
  ('CD', 'Congo - Kinshasa', true),
  ('CF', 'Central African Republic', true),
  ('CG', 'Congo - Brazzaville', true),
  ('CH', 'Switzerland', true),
  ('CI', 'Côte d’Ivoire', true),
  ('CK', 'Cook Islands', true),
  ('CL', 'Chile', true),
  ('CM', 'Cameroon', true),
  ('CN', 'China', true),
  ('CO', 'Colombia', true),
  ('CR', 'Costa Rica', true),
  ('CU', 'Cuba', true),
  ('CV', 'Cape Verde', true),
  ('CW', 'Curaçao', true),
  ('CX', 'Christmas Island', true),
  ('CY', 'Cyprus', true),
  ('CZ', 'Czechia', true),
  ('DE', 'Germany', true),
  ('DJ', 'Djibouti', true),
  ('DK', 'Denmark', true),
  ('DM', 'Dominica', true),
  ('DO', 'Dominican Republic', true),
  ('DZ', 'Algeria', true),
  ('EC', 'Ecuador', true),
  ('EE', 'Estonia', true),
  ('EG', 'Egypt', true),
  ('EH', 'Western Sahara', true),
  ('ER', 'Eritrea', true),
  ('ES', 'Spain', true),
  ('ET', 'Ethiopia', true),
  ('FI', 'Finland', true),
  ('FJ', 'Fiji', true),
  ('FK', 'Falkland Islands', true),
  ('FM', 'Micronesia', true),
  ('FO', 'Faroe Islands', true),
  ('FR', 'France', true),
  ('GA', 'Gabon', true),
  ('GB', 'United Kingdom', true),
  ('GD', 'Grenada', true),
  ('GE', 'Georgia', true),
  ('GF', 'French Guiana', true),
  ('GG', 'Guernsey', true),
  ('GH', 'Ghana', true),
  ('GI', 'Gibraltar', true),
  ('GL', 'Greenland', true),
  ('GM', 'Gambia', true),
  ('GN', 'Guinea', true),
  ('GP', 'Guadeloupe', true),
  ('GQ', 'Equatorial Guinea', true),
  ('GR', 'Greece', true),
  ('GS', 'South Georgia & South Sandwich Islands', true),
  ('GT', 'Guatemala', true),
  ('GU', 'Guam', true),
  ('GW', 'Guinea-Bissau', true),
  ('GY', 'Guyana', true),
  ('HK', 'Hong Kong SAR China', true),
  ('HM', 'Heard & McDonald Islands', true),
  ('HN', 'Honduras', true),
  ('HR', 'Croatia', true),
  ('HT', 'Haiti', true),
  ('HU', 'Hungary', true),
  ('ID', 'Indonesia', true),
  ('IE', 'Ireland', true),
  ('IL', 'Israel', true),
  ('IM', 'Isle of Man', true),
  ('IN', 'India', true),
  ('IO', 'British Indian Ocean Territory', true),
  ('IQ', 'Iraq', true),
  ('IR', 'Iran', true),
  ('IS', 'Iceland', true),
  ('IT', 'Italy', true),
  ('JE', 'Jersey', true),
  ('JM', 'Jamaica', true),
  ('JO', 'Jordan', true),
  ('JP', 'Japan', true),
  ('KE', 'Kenya', true),
  ('KG', 'Kyrgyzstan', true),
  ('KH', 'Cambodia', true),
  ('KI', 'Kiribati', true),
  ('KM', 'Comoros', true),
  ('KN', 'St. Kitts & Nevis', true),
  ('KP', 'North Korea', true),
  ('KR', 'South Korea', true),
  ('KW', 'Kuwait', true),
  ('KY', 'Cayman Islands', true),
  ('KZ', 'Kazakhstan', true),
  ('LA', 'Laos', true),
  ('LB', 'Lebanon', true),
  ('LC', 'St. Lucia', true),
  ('LI', 'Liechtenstein', true),
  ('LK', 'Sri Lanka', true),
  ('LR', 'Liberia', true),
  ('LS', 'Lesotho', true),
  ('LT', 'Lithuania', true),
  ('LU', 'Luxembourg', true),
  ('LV', 'Latvia', true),
  ('LY', 'Libya', true),
  ('MA', 'Morocco', true),
  ('MC', 'Monaco', true),
  ('MD', 'Moldova', true),
  ('ME', 'Montenegro', true),
  ('MF', 'St. Martin', true),
  ('MG', 'Madagascar', true),
  ('MH', 'Marshall Islands', true),
  ('MK', 'North Macedonia', true),
  ('ML', 'Mali', true),
  ('MM', 'Myanmar (Burma)', true),
  ('MN', 'Mongolia', true),
  ('MO', 'Macao SAR China', true),
  ('MP', 'Northern Mariana Islands', true),
  ('MQ', 'Martinique', true),
  ('MR', 'Mauritania', true),
  ('MS', 'Montserrat', true),
  ('MT', 'Malta', true),
  ('MU', 'Mauritius', true),
  ('MV', 'Maldives', true),
  ('MW', 'Malawi', true),
  ('MX', 'Mexico', true),
  ('MY', 'Malaysia', true),
  ('MZ', 'Mozambique', true),
  ('NA', 'Namibia', true),
  ('NC', 'New Caledonia', true),
  ('NE', 'Niger', true),
  ('NF', 'Norfolk Island', true),
  ('NG', 'Nigeria', true),
  ('NI', 'Nicaragua', true),
  ('NL', 'Netherlands', true),
  ('NO', 'Norway', true),
  ('NP', 'Nepal', true),
  ('NR', 'Nauru', true),
  ('NU', 'Niue', true),
  ('NZ', 'New Zealand', true),
  ('OM', 'Oman', true),
  ('PA', 'Panama', true),
  ('PE', 'Peru', true),
  ('PF', 'French Polynesia', true),
  ('PG', 'Papua New Guinea', true),
  ('PH', 'Philippines', true),
  ('PK', 'Pakistan', true),
  ('PL', 'Poland', true),
  ('PM', 'St. Pierre & Miquelon', true),
  ('PN', 'Pitcairn Islands', true),
  ('PR', 'Puerto Rico', true),
  ('PS', 'Palestinian Territories', true),
  ('PT', 'Portugal', true),
  ('PW', 'Palau', true),
  ('PY', 'Paraguay', true),
  ('QA', 'Qatar', true),
  ('RE', 'Réunion', true),
  ('RO', 'Romania', true),
  ('RS', 'Serbia', true),
  ('RU', 'Russia', true),
  ('RW', 'Rwanda', true),
  ('SA', 'Saudi Arabia', true),
  ('SB', 'Solomon Islands', true),
  ('SC', 'Seychelles', true),
  ('SD', 'Sudan', true),
  ('SE', 'Sweden', true),
  ('SG', 'Singapore', true),
  ('SH', 'St. Helena', true),
  ('SI', 'Slovenia', true),
  ('SJ', 'Svalbard & Jan Mayen', true),
  ('SK', 'Slovakia', true),
  ('SL', 'Sierra Leone', true),
  ('SM', 'San Marino', true),
  ('SN', 'Senegal', true),
  ('SO', 'Somalia', true),
  ('SR', 'Suriname', true),
  ('SS', 'South Sudan', true),
  ('ST', 'São Tomé & Príncipe', true),
  ('SV', 'El Salvador', true),
  ('SX', 'Sint Maarten', true),
  ('SY', 'Syria', true),
  ('SZ', 'Eswatini', true),
  ('TC', 'Turks & Caicos Islands', true),
  ('TD', 'Chad', true),
  ('TF', 'French Southern Territories', true),
  ('TG', 'Togo', true),
  ('TH', 'Thailand', true),
  ('TJ', 'Tajikistan', true),
  ('TK', 'Tokelau', true),
  ('TL', 'Timor-Leste', true),
  ('TM', 'Turkmenistan', true),
  ('TN', 'Tunisia', true),
  ('TO', 'Tonga', true),
  ('TR', 'Türkiye', true),
  ('TT', 'Trinidad & Tobago', true),
  ('TV', 'Tuvalu', true),
  ('TW', 'Taiwan', true),
  ('TZ', 'Tanzania', true),
  ('UA', 'Ukraine', true),
  ('UG', 'Uganda', true),
  ('UM', 'U.S. Outlying Islands', true),
  ('US', 'United States', true),
  ('UY', 'Uruguay', true),
  ('UZ', 'Uzbekistan', true),
  ('VA', 'Vatican City', true),
  ('VC', 'St. Vincent & Grenadines', true),
  ('VE', 'Venezuela', true),
  ('VG', 'British Virgin Islands', true),
  ('VI', 'U.S. Virgin Islands', true),
  ('VN', 'Vietnam', true),
  ('VU', 'Vanuatu', true),
  ('WF', 'Wallis & Futuna', true),
  ('WS', 'Samoa', true),
  ('YE', 'Yemen', true),
  ('YT', 'Mayotte', true),
  ('ZA', 'South Africa', true),
  ('ZM', 'Zambia', true),
  ('ZW', 'Zimbabwe', true)
on conflict (code) do update
set
  name = excluded.name,
  is_active = true;
