do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'level_definitions',
    'badge_definitions',
    'badge_requirement_definitions',
    'virtue_definitions',
    'saint_definitions',
    'demon_definitions',
    'demon_attacks',
    'demon_defenses',
    'challenge_definitions'
  ]
  loop
    execute format(
      'alter table competition.%I add column if not exists translations jsonb not null default ''{}''::jsonb',
      table_name
    );
    execute format(
      'alter table competition.%I drop constraint if exists %I',
      table_name,
      table_name || '_translations_check'
    );
    execute format(
      'alter table competition.%I add constraint %I check (
        jsonb_typeof(translations) = ''object''
        and translations - ''es'' = ''{}''::jsonb
        and (not (translations ? ''es'') or jsonb_typeof(translations -> ''es'') = ''object'')
      )',
      table_name,
      table_name || '_translations_check'
    );
  end loop;
end
$$;

alter table app.examination_of_conscience_questions
  add column if not exists translations jsonb not null default '{}'::jsonb;
alter table app.examination_of_conscience_questions
  drop constraint if exists examination_of_conscience_questions_translations_check;
alter table app.examination_of_conscience_questions
  add constraint examination_of_conscience_questions_translations_check check (
    jsonb_typeof(translations) = 'object'
    and translations - 'es' = '{}'::jsonb
    and (not (translations ? 'es') or jsonb_typeof(translations -> 'es') = 'object')
  );

create or replace function platform.apply_spanish_catalog_translations()
returns void
language plpgsql
set search_path = ''
as $$
begin
  update competition.level_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('awakened', jsonb_build_object('name', 'Despierto', 'description', 'Comienza a reconocer la batalla.')),
    ('seeker', jsonb_build_object('name', 'Buscador', 'description', 'Comienza a formar hábitos diarios.')),
    ('disciple', jsonb_build_object('name', 'Discípulo', 'description', 'Sigue una regla de vida constante.')),
    ('fighter', jsonb_build_object('name', 'Luchador', 'description', 'Resiste las tentaciones recurrentes.')),
    ('guardian', jsonb_build_object('name', 'Guardián', 'description', 'Protege su entorno y sus relaciones.')),
    ('servant', jsonb_build_object('name', 'Servidor', 'description', 'Sirve a los demás con regularidad.')),
    ('brother', jsonb_build_object('name', 'Hermano', 'description', 'Apoya a otros hombres.')),
    ('leader', jsonb_build_object('name', 'Líder', 'description', 'Guía con el ejemplo.')),
    ('witness', jsonb_build_object('name', 'Testigo', 'description', 'Vive la fe de manera pública y constante.')),
    ('persevering_disciple', jsonb_build_object('name', 'Discípulo perseverante', 'description', 'Continúa fielmente a lo largo del tiempo.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.badge_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('FIRST_ROSARY', jsonb_build_object('name', 'Primer Rosario', 'description', 'Reza tu primer rosario completo.')),
    ('SCRIPTURE_SEEKER', jsonb_build_object('name', 'Buscador de la Escritura', 'description', 'Completa cinco sesiones de lectura de la Escritura.')),
    ('PRAYER_STREAK', jsonb_build_object('name', 'Racha de oración', 'description', 'Ora durante siete días consecutivos.')),
    ('COMMUNITY_HELPER', jsonb_build_object('name', 'Servidor de la comunidad', 'description', 'Completa tres obras de servicio.')),
    ('BELT_OF_TRUTH', jsonb_build_object('name', 'Cinturón de la verdad', 'description', 'Revístete con el Cinturón de la verdad practicando cada día la honestidad y la integridad.')),
    ('SHIELD_OF_FAITH', jsonb_build_object('name', 'Escudo de la fe', 'description', 'Desbloquea el Escudo de la fe mediante la oración constante, la Escritura y la confianza en las dificultades.', 'rules', jsonb_build_object('virtue', 'faith', 'requirements', jsonb_build_array(jsonb_build_object('type', 'prayer_days', 'value', 7, 'description', 'Siete días de oración'), jsonb_build_object('type', 'scripture_plan_completed', 'value', 1, 'description', 'Un plan de lectura de la Escritura completado'), jsonb_build_object('type', 'trust_act_during_difficulty', 'value', 1, 'description', 'Un acto de confianza durante una dificultad'))))),
    ('SWORD_OF_THE_SPIRIT', jsonb_build_object('name', 'Espada del Espíritu', 'description', 'Desbloquea la Espada del Espíritu guardando la Palabra de Dios en tu corazón.')),
    ('HELMET_OF_SALVATION', jsonb_build_object('name', 'Yelmo de la salvación', 'description', 'Desbloquea el Yelmo de la salvación renovando la esperanza y protegiendo tu mente.')),
    ('BOOTS_OF_READINESS', jsonb_build_object('name', 'Calzado de la disponibilidad', 'description', 'Desbloquea el Calzado de la disponibilidad estando listo para servir y llevar la paz.')),
    ('BREASTPLATE_OF_RIGHTEOUSNESS', jsonb_build_object('name', 'Coraza de la justicia', 'description', 'Desbloquea la Coraza de la justicia mediante decisiones rectas y constantes.')),
    ('CHURCH_SCHEDULE_STEWARD', jsonb_build_object('name', 'Custodio de horarios parroquiales', 'description', 'Mantén actualizado el horario de culto de una iglesia. Se obtiene por cada actualización aprobada.')),
    ('PRAYER_INTENTION_1', jsonb_build_object('name', 'Primera intención', 'description', 'Comparte una intención de oración comunitaria aprobada por un administrador.')),
    ('PRAYER_INTENTION_3', jsonb_build_object('name', 'Intercesor fiel', 'description', 'Comparte tres intenciones de oración comunitaria aprobadas por un administrador.')),
    ('PRAYER_INTENTION_7', jsonb_build_object('name', 'Defensor de la oración', 'description', 'Comparte siete intenciones de oración comunitaria aprobadas por un administrador.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.badge_requirement_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('daily_honesty_reflection', jsonb_build_object('description', 'Completa siete reflexiones diarias de honestidad.')),
    ('prayer_days', jsonb_build_object('description', 'Siete días de oración.')),
    ('scripture_plan_completed', jsonb_build_object('description', 'Un plan de lectura de la Escritura completado.')),
    ('trust_act_during_difficulty', jsonb_build_object('description', 'Un acto de confianza durante una dificultad.')),
    ('scripture_reading_sessions', jsonb_build_object('description', 'Completa diez sesiones de lectura de la Escritura.')),
    ('daily_prayer_streak', jsonb_build_object('description', 'Mantén una racha de oración de catorce días.')),
    ('service_acts', jsonb_build_object('description', 'Completa cinco obras de servicio.')),
    ('daily_rule_of_life_streak', jsonb_build_object('description', 'Mantén una racha de veintiún días cumpliendo tu regla de vida.'))
  ) as source(requirement_type, value)
  where target.requirement_type = source.requirement_type;

  update competition.virtue_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('FAITH', jsonb_build_object('name', 'Fe', 'description', 'Confianza en Dios y disposición para permanecer cerca de Él.')),
    ('DISCIPLINE', jsonb_build_object('name', 'Disciplina', 'description', 'Elegir el bien incluso cuando falta la motivación.')),
    ('COURAGE', jsonb_build_object('name', 'Valentía', 'description', 'Afrontar el miedo, la incomodidad, la responsabilidad y las verdades difíciles.')),
    ('WISDOM', jsonb_build_object('name', 'Sabiduría', 'description', 'Reconocer la verdad y elegir la siguiente acción buena.')),
    ('CHARITY', jsonb_build_object('name', 'Caridad', 'description', 'Amar a los demás con paciencia, misericordia, servicio y verdad.')),
    ('PURITY', jsonb_build_object('name', 'Pureza', 'description', 'Ver a las personas con dignidad y custodiar el corazón y la imaginación.')),
    ('PERSEVERANCE', jsonb_build_object('name', 'Perseverancia', 'description', 'Volver a empezar y continuar después de una dificultad o un fracaso.')),
    ('HUMILITY', jsonb_build_object('name', 'Humildad', 'description', 'Vivir en la verdad, sin exaltarse ni despreciarse.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.challenge_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('DAILY_ROSARY', jsonb_build_object('title', 'Rosario diario', 'description', 'Reza hoy un rosario completo.')),
    ('DAILY_SCRIPTURE', jsonb_build_object('title', 'Escritura diaria', 'description', 'Completa hoy una lectura de la Escritura.')),
    ('WEEKLY_SERVICE', jsonb_build_object('title', 'Sirve a tu prójimo', 'description', 'Completa tres obras de servicio esta semana.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.saint_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('IGNATIUS_OF_LOYOLA', jsonb_build_object('name', 'San Ignacio de Loyola', 'description', 'Un mentor para el discernimiento y la atención ordenada.')),
    ('JOSEPH', jsonb_build_object('name', 'San José', 'description', 'Un mentor para el trabajo constante, la responsabilidad y el servicio silencioso.')),
    ('FRANCIS_DE_SALES', jsonb_build_object('name', 'San Francisco de Sales', 'description', 'Un mentor para la mansedumbre y la palabra paciente.')),
    ('THERESE_OF_LISIEUX', jsonb_build_object('name', 'Santa Teresa de Lisieux', 'description', 'Una mentora para el amor escondido y el caminito.')),
    ('BENEDICT', jsonb_build_object('name', 'San Benito de Nursia', 'description', 'Un mentor para el trabajo acompañado de oración, la estabilidad y el orden santo.')),
    ('FRANCIS_OF_ASSISI', jsonb_build_object('name', 'San Francisco de Asís', 'description', 'Un mentor para la gratitud, la sencillez y la alegría por el bien de los demás.')),
    ('JOAN_OF_ARC', jsonb_build_object('name', 'Santa Juana de Arco', 'description', 'Una mentora para la obediencia valiente a pesar del miedo.')),
    ('PETER', jsonb_build_object('name', 'San Pedro', 'description', 'Un mentor para el arrepentimiento y el regreso después del fracaso.')),
    ('PHILIP_NERI', jsonb_build_object('name', 'San Felipe Neri', 'description', 'Un mentor para la caridad alegre y la sabiduría práctica.')),
    ('LAWRENCE', jsonb_build_object('name', 'San Lorenzo', 'description', 'Un mentor para la generosidad y el amor a las personas por encima de las posesiones.')),
    ('MARIA_GORETTI', jsonb_build_object('name', 'Santa María Goretti', 'description', 'Una mentora para la pureza, la dignidad, el perdón y la valentía.')),
    ('BLESSED_VIRGIN_MARY', jsonb_build_object('name', 'Santísima Virgen María', 'description', 'Una mentora maternal para la fe, la humildad y la esperanza firme.')),
    ('OUR_LADY_QUEEN_OF_HEAVEN', jsonb_build_object('name', 'Nuestra Señora, Reina del Cielo', 'description', 'Una mentora para la oración, la confianza y la esperanza en Cristo.')),
    ('ANTHONY_OF_PADUA', jsonb_build_object('name', 'San Antonio de Padua', 'description', 'Un mentor para la perseverancia, el aprendizaje y el cuidado de los pobres.')),
    ('AUGUSTINE_OF_HIPPO', jsonb_build_object('name', 'San Agustín de Hipona', 'description', 'Un mentor para la conversión, la verdad y los corazones que vuelven a Dios.')),
    ('CATHERINE_OF_SIENA', jsonb_build_object('name', 'Santa Catalina de Siena', 'description', 'Una mentora para la valentía, la verdad y el amor a la Iglesia.')),
    ('CECILIA', jsonb_build_object('name', 'Santa Cecilia', 'description', 'Una mentora para la alabanza alegre, la pureza y el testimonio valiente.')),
    ('DOMINIC', jsonb_build_object('name', 'Santo Domingo', 'description', 'Un mentor para la predicación, el estudio y la caridad arraigada en la verdad.')),
    ('DYMPHNA', jsonb_build_object('name', 'Santa Dimpna', 'description', 'Una mentora para la compasión, la paz interior y la confianza valiente.')),
    ('FRANCIS_XAVIER', jsonb_build_object('name', 'San Francisco Javier', 'description', 'Un mentor para la misión, la generosidad y el anuncio de Cristo.')),
    ('JOHN_PAUL_II', jsonb_build_object('name', 'San Juan Pablo II', 'description', 'Un mentor para la dignidad humana, la valentía y la fe alegre.')),
    ('JOHN_THE_EVANGELIST', jsonb_build_object('name', 'San Juan Evangelista', 'description', 'Un mentor para la amistad fiel, el amor y el testimonio audaz.')),
    ('JUAN_DIEGO', jsonb_build_object('name', 'San Juan Diego', 'description', 'Un mentor para la humildad, la obediencia y el compartir la esperanza.')),
    ('MAXIMILIAN_KOLBE', jsonb_build_object('name', 'San Maximiliano Kolbe', 'description', 'Un mentor para el amor entregado, la valentía y la esperanza en el sufrimiento.')),
    ('MICHAEL_THE_ARCHANGEL', jsonb_build_object('name', 'San Miguel Arcángel', 'description', 'Un mentor para la valentía espiritual, la protección y la fidelidad a Dios.')),
    ('MONICA', jsonb_build_object('name', 'Santa Mónica', 'description', 'Una mentora para la oración paciente, la perseverancia y el amor esperanzado.')),
    ('NICHOLAS', jsonb_build_object('name', 'San Nicolás', 'description', 'Un mentor para la generosidad discreta, el cuidado de los niños y la compasión.')),
    ('PADRE_PIO', jsonb_build_object('name', 'San Pío de Pietrelcina', 'description', 'Un mentor para la oración, el sufrimiento ofrecido con amor y la reconciliación.')),
    ('PATRICK', jsonb_build_object('name', 'San Patricio', 'description', 'Un mentor para la valentía misionera, el perdón y el servicio fiel.')),
    ('PAUL', jsonb_build_object('name', 'San Pablo', 'description', 'Un mentor para la conversión, el celo y el anuncio valiente del Evangelio.')),
    ('SEBASTIAN', jsonb_build_object('name', 'San Sebastián', 'description', 'Un mentor para la valentía firme, la fidelidad y la esperanza en la prueba.')),
    ('TERESA_OF_AVILA', jsonb_build_object('name', 'Santa Teresa de Ávila', 'description', 'Una mentora para la oración interior, la amistad con Dios y la valentía.')),
    ('TERESA_OF_CALCUTTA', jsonb_build_object('name', 'Santa Teresa de Calcuta', 'description', 'Una mentora para el servicio misericordioso, la sencillez y el amor a los pobres.')),
    ('THOMAS_AQUINAS', jsonb_build_object('name', 'Santo Tomás de Aquino', 'description', 'Un mentor para la fe, la razón, el estudio y el amor a la verdad.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.demon_definitions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('SCROLLZILLA', jsonb_build_object('name', 'Scrollzilla', 'title', 'El desplazador interminable', 'description', 'Una diminuta molestia roja con pulgares enormes que se alimenta de notificaciones, videos cortos y de posponer la hora de dormir.', 'silly_personality', 'Carga tres teléfonos, pero nunca recuerda dónde dejó ninguno.', 'saint_mentor_reason', 'El discernimiento y la atención ordenada revelan los trucos de Scrollzilla.')),
    ('SNOOZLEUMP', jsonb_build_object('name', 'Snoozleump', 'title', 'El comandante de las cobijas', 'description', 'Una masa soñolienta que declara que toda responsabilidad puede esperar sin problema hasta mañana.', 'silly_personality', 'Usa una almohada como corona y ronca durante sus propios discursos.', 'saint_mentor_reason', 'El trabajo constante, la responsabilidad y el servicio silencioso debilitan a Snoozleump.')),
    ('GRUMBLEPUFF', jsonb_build_object('name', 'Grumblepuff', 'title', 'La nube de quejas', 'description', 'Un pequeño cascarrabias humeante que convierte cualquier inconveniente en una tragedia de cinco actos.', 'silly_personality', 'Se enfada si la sopa está muy caliente y todavía más cuando se enfría.', 'saint_mentor_reason', 'La mansedumbre y la palabra paciente contrarrestan directamente la ira reactiva.')),
    ('BRAGGLESNOUT', jsonb_build_object('name', 'Bragglesnout', 'title', 'El pequeño trompetista', 'description', 'Un presumido morado con cuernos que anuncia cada buena obra con trompetas imaginarias.', 'silly_personality', 'Se entrega trofeos por asistir a reuniones que él mismo convocó.', 'saint_mentor_reason', 'Su caminito de amor escondido vence la necesidad de impresionar.')),
    ('SNACKASAURUS', jsonb_build_object('name', 'Snackasaurus', 'title', 'El comelón insaciable', 'description', 'Un demonio redondo que insiste en que toda emoción necesita un bocadillo y todo bocadillo necesita otro.', 'silly_personality', 'Guarda pastelitos de emergencia dentro de un pastelito de emergencia.', 'saint_mentor_reason', 'La moderación, el orden y el ritmo hacen que el exceso pierda su poder.')),
    ('PEEKABOOZE', jsonb_build_object('name', 'Peekabooze', 'title', 'El duende de la comparación', 'description', 'Un duende verde que espía la vida de los demás y elimina de la imagen todas sus luchas.', 'silly_personality', 'Tiene binoculares que solo apuntan a las bendiciones ajenas.', 'saint_mentor_reason', 'La gratitud, la sencillez y la alegría por el bien ajeno desenmascaran la envidia.')),
    ('WOBBLEKNEES', jsonb_build_object('name', 'Wobbleknees', 'title', 'El catastrofista cobarde', 'description', 'Un demonio nervioso que predice doce desastres antes del desayuno y se esconde tras un escudo diminuto.', 'silly_personality', 'Grita cada vez que su propia capa lo roza.', 'saint_mentor_reason', 'La obediencia valiente a pesar del miedo vence sus exageraciones.')),
    ('WHISPERWHOMP', jsonb_build_object('name', 'Whisperwhomp', 'title', 'El murmurador del desánimo', 'description', 'Una bola de pelusa sombría que susurra que los fracasos pasados vuelven inútil cualquier esfuerzo futuro.', 'silly_personality', 'Practica suspiros dramáticos frente al espejo.', 'saint_mentor_reason', 'Su arrepentimiento y regreso después del fracaso muestran que caer no es el final.')),
    ('GOSSIPGOB', jsonb_build_object('name', 'Gossipgob', 'title', 'El coleccionista de rumores', 'description', 'Un duende de orejas largas que colecciona historias a medias y agrega gratis tres detalles dramáticos.', 'silly_personality', 'Comienza cada frase con «Probablemente no debería decir esto, pero…».', 'saint_mentor_reason', 'La alegría, la caridad y la sabiduría práctica desenmascaran las palabras descuidadas.')),
    ('SHINYGRAB', jsonb_build_object('name', 'Shinygrab', 'title', 'El duende de las compras', 'description', 'Un duende de ojos dorados que cree que toda oferta por tiempo limitado es una emergencia espiritual.', 'silly_personality', 'Compra cajas para organizar las cajas que ya compró.', 'saint_mentor_reason', 'La generosidad y el amor a las personas por encima de las posesiones vencen a Shinygrab.')),
    ('FOGGLES', jsonb_build_object('name', 'Foggles', 'title', 'La nube de confusión', 'description', 'Un ojo azul flotante rodeado de niebla que hace que toda decisión sencilla parezca una tesis doctoral.', 'silly_personality', 'Necesita un diagrama para decidir si debe hacer un diagrama.', 'saint_mentor_reason', 'El discernimiento, la claridad y las decisiones ordenadas dispersan la niebla.')),
    ('SNEAKYPEEKY', jsonb_build_object('name', 'Sneakypeeky', 'title', 'El merodeador de la pantalla', 'description', 'Un diablillo rosado con alas que esconde contenido dañino detrás del aburrimiento, el secreto y «solo una mirada».', 'silly_personality', 'Usa lentes de sol en interiores porque cree que lo vuelven invisible.', 'saint_mentor_reason', 'La pureza, la dignidad, el perdón y la valentía se enfrentan a la cosificación y al secreto.', 'safety_note', 'Ante una conducta compulsiva recurrente, busca apoyo confidencial de un adulto de confianza, un sacerdote, un consejero o un profesional cualificado; el software no es un tratamiento.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.demon_attacks as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('ALL_OR_NOTHING', jsonb_build_object('name', 'Drama de dieta', 'description', 'Convierte una decisión imperfecta en una rendición completa.')),
    ('AVOID_FIRST_STEP', jsonb_build_object('name', 'Quizá nunca sea más seguro', 'description', 'Hace que el primer paso parezca más peligroso que evitarlo.')),
    ('AVOID_HARD_CONVERSATION', jsonb_build_object('name', 'Volcán silencioso', 'description', 'Evita una conversación sincera mientras crece el resentimiento.')),
    ('AVOID_THE_TASK', jsonb_build_object('name', 'Procrastinación con apariencia productiva', 'description', 'Hace que la distracción parezca útil mientras la tarea real queda intacta.')),
    ('DO_NOT_TRY', jsonb_build_object('name', 'Derrotado de antemano', 'description', 'Pierde convincentemente las batallas antes de que comiencen.')),
    ('EMOTIONAL_EATING', jsonb_build_object('name', 'Invocación del bocadillo triste', 'description', 'Usa la comida para evitar procesar las emociones.')),
    ('FAILURE_DEFINES_YOU', jsonb_build_object('name', 'La etiqueta permanente', 'description', 'Trata un fracaso como si definiera por completo a la persona.')),
    ('FEAR_COMMITMENT', jsonb_build_object('name', 'Parálisis ante la decisión', 'description', 'Hace que comprometerse parezca más peligroso que permanecer indeciso.')),
    ('FORGOTTEN_BLESSINGS', jsonb_build_object('name', 'Venda ante las bendiciones', 'description', 'Oculta lo que ya es bueno en la vida de la persona.')),
    ('GOD_IS_DISTANT', jsonb_build_object('name', 'Él no está escuchando', 'description', 'Tienta a abandonar la oración cuando falta el consuelo.')),
    ('HOARD_USEFUL_ITEMS', jsonb_build_object('name', 'La montaña del «algún día»', 'description', 'Mantiene bienes útiles lejos de quienes los necesitan.')),
    ('IMPULSE_PURCHASE', jsonb_build_object('name', 'Compra ahora, discierne nunca', 'description', 'Convierte un deseo en una compra inmediata.')),
    ('LATE_NIGHT_SCROLLING', jsonb_build_object('name', 'Un video más', 'description', 'Mantiene a la persona desplazándose por la pantalla después de la hora de dormir.')),
    ('LATE_NIGHT_WEAKNESS', jsonb_build_object('name', 'Emboscada de medianoche', 'description', 'Aprovecha el cansancio, la privacidad y el uso desordenado de pantallas.')),
    ('MOCK_PERSON', jsonb_build_object('name', 'Comedia a costa ajena', 'description', 'Usa la debilidad de otra persona para llamar la atención.')),
    ('MORAL_SUPERIORITY', jsonb_build_object('name', 'Orgullo con cara de preocupación', 'description', 'Disfraza el juicio como preocupación.')),
    ('NEED_TO_BE_RIGHT', jsonb_build_object('name', 'En realidad, técnicamente…', 'description', 'Convierte toda conversación en una competencia.')),
    ('NOTIFICATION_STORM', jsonb_build_object('name', 'Confeti de notificaciones', 'description', 'Interrumpe la oración, el trabajo y el tiempo en familia.')),
    ('OVERTHINK_DECISION', jsonb_build_object('name', 'Desfile infinito de opciones', 'description', 'Agrega opciones innecesarias hasta que ninguna acción parece posible.')),
    ('POSSESSION_IDENTITY', jsonb_build_object('name', 'Eres lo que posees', 'description', 'Vincula el valor personal con las posesiones y el estatus.')),
    ('QUIT_EARLY', jsonb_build_object('name', 'Salida de emergencia por todas partes', 'description', 'Anima a rendirse antes de haber hecho suficiente esfuerzo.')),
    ('REFUSE_CORRECTION', jsonb_build_object('name', 'Armadura de excusas', 'description', 'Rechaza una corrección útil antes de considerarla.')),
    ('RESENT_SUCCESS', jsonb_build_object('name', '¿Por qué ellos?', 'description', 'Convierte el éxito de otra persona en resentimiento.')),
    ('RESENTMENT_LOOP', jsonb_build_object('name', 'Repetición de la ofensa', 'description', 'Repite mentalmente una ofensa hasta que parece más grande.')),
    ('SECOND_PORTION', jsonb_build_object('name', 'El hechizo de rellenar el plato', 'description', 'Empuja a comer más allá de una satisfacción razonable.')),
    ('SECRECY', jsonb_build_object('name', 'Nadie tiene que saberlo', 'description', 'Usa el aislamiento y la vergüenza para impedir que se busque ayuda.')),
    ('SEEK_ENDLESS_SIGNS', jsonb_build_object('name', 'Una señal más', 'description', 'Evita decisiones razonables exigiendo certeza absoluta.')),
    ('SEEK_PRAISE', jsonb_build_object('name', 'Aspiradora de aplausos', 'description', 'Hace que las buenas acciones parezcan inútiles si nadie las nota.')),
    ('SERVICE_AVOIDANCE', jsonb_build_object('name', 'Alguien más lo hará', 'description', 'Hace que servir parezca incómodo y opcional.')),
    ('SHARE_RUMOR', jsonb_build_object('name', 'Pásalo', 'description', 'Anima a compartir información no verificada o innecesaria.')),
    ('SHARP_REPLY', jsonb_build_object('name', 'Trueno instantáneo del teclado', 'description', 'Empuja a responder con dureza antes de comprender.')),
    ('SNOOZE_AGAIN', jsonb_build_object('name', 'El sagrado botón de posponer', 'description', 'Anima a retrasar repetidamente el levantarse.')),
    ('SOCIAL_COMPARISON', jsonb_build_object('name', 'Visión de momentos destacados', 'description', 'Compara la vida cotidiana con imágenes seleccionadas de los demás.')),
    ('TOMORROW_TRAP', jsonb_build_object('name', 'Mañana será mucho mejor', 'description', 'Traslada el trabajo necesario a un futuro perfecto imaginario.')),
    ('TRIGGERING_CONTENT', jsonb_build_object('name', 'Solo una mirada', 'description', 'Presenta contenido dañino o cosificador como curiosidad inofensiva.')),
    ('WORST_CASE_LOOP', jsonb_build_object('name', 'Presentación de desastres', 'description', 'Repite desenlaces imaginarios cada vez peores.'))
  ) as source(code, value)
  where target.code = source.code;

  update competition.demon_defenses as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('ADMIT_MISTAKE', jsonb_build_object('name', 'Suelta el trofeo', 'challenge', 'Admite claramente un error sin añadir una excusa.')),
    ('ASK_FOR_SUPPORT', jsonb_build_object('name', 'Llama a los refuerzos', 'challenge', 'Pide a una persona de confianza oración, ánimo o acompañamiento.')),
    ('CALM_CONVERSATION', jsonb_build_object('name', 'Di la verdad con amabilidad', 'challenge', 'Ten una conversación directa y respetuosa en vez de evitarla o explotar.')),
    ('CONGRATULATE_PERSON', jsonb_build_object('name', 'Celebra su victoria', 'challenge', 'Felicita a alguien de manera sincera y específica.')),
    ('CONTACT_ACCOUNTABILITY', jsonb_build_object('name', 'Rompe el secreto', 'challenge', 'Contacta a una persona de confianza y pídele apoyo de forma sencilla.')),
    ('DEVICE_BOUNDARY', jsonb_build_object('name', 'Custodia la puerta', 'challenge', 'Saca el dispositivo del espacio privado y activa las restricciones de contenido.')),
    ('EXAMINE_MOTIVE', jsonb_build_object('name', 'Mira el espejo', 'challenge', 'Escribe por qué querías compartir la información antes de hablar.')),
    ('FACTS_VALUES_NEXT_STEP', jsonb_build_object('name', 'Despeja la niebla', 'challenge', 'Escribe los hechos conocidos, el valor implicado y el siguiente paso razonable.')),
    ('FINISH_SMALL_COMMITMENT', jsonb_build_object('name', 'Mantén la línea', 'challenge', 'Termina un compromiso pequeño antes de cambiar de dirección.')),
    ('FIVE_BLESSINGS', jsonb_build_object('name', 'Abre el libro de bendiciones', 'challenge', 'Escribe cinco bendiciones concretas de hoy.')),
    ('FOCUS_MODE', jsonb_build_object('name', 'Silencia las campanas', 'challenge', 'Activa el modo de concentración y completa una sesión ininterrumpida de 25 minutos.')),
    ('GIVE_ITEM', jsonb_build_object('name', 'Abre el granero', 'challenge', 'Dona o regala un objeto útil que esté en buenas condiciones.')),
    ('HIDDEN_KINDNESS', jsonb_build_object('name', 'Victoria invisible', 'challenge', 'Realiza un acto de bondad y no se lo cuentes a nadie.')),
    ('HIDDEN_SERVICE', jsonb_build_object('name', 'Manos silenciosas', 'challenge', 'Completa una obra útil de servicio sin buscar reconocimiento.')),
    ('LEAVE_TRIGGER', jsonb_build_object('name', 'Sal de la habitación', 'challenge', 'Cierra inmediatamente el contenido y aléjate físicamente del entorno que provoca la tentación.')),
    ('LISTEN_FULLY', jsonb_build_object('name', 'Cierra la trompeta', 'challenge', 'Escucha sin interrumpir ni preparar tu respuesta.')),
    ('MAKE_BED', jsonb_build_object('name', 'Primera victoria', 'challenge', 'Levántate y tiende la cama de inmediato.')),
    ('MINDFUL_PORTION', jsonb_build_object('name', 'Pacto de un solo plato', 'challenge', 'Elige una porción razonable y come sin mirar una pantalla.')),
    ('NEED_TEST', jsonb_build_object('name', 'Necesidad, uso y costo', 'challenge', 'Escribe qué ocurrirá si no lo compras, con qué frecuencia lo usarás y cuál es su costo total.')),
    ('ONE_BRAVE_STEP', jsonb_build_object('name', 'Un paso adelante', 'challenge', 'Da un paso concreto hacia la responsabilidad que has evitado.')),
    ('OUR_FATHER_SLOWLY', jsonb_build_object('name', 'Confía en el Padre', 'challenge', 'Reza lentamente el Padrenuestro e identifica la siguiente acción que puedes controlar.')),
    ('PHONE_SIX_FEET_AWAY', jsonb_build_object('name', 'El exilio de dos metros', 'challenge', 'Coloca el teléfono al menos a dos metros de distancia durante 30 minutos o antes de dormir.')),
    ('PRAY_AND_DECIDE', jsonb_build_object('name', 'Ora y luego actúa', 'challenge', 'Ora brevemente, elige entre opciones moralmente buenas y fija una fecha límite.')),
    ('PRAY_FOR_PERSON', jsonb_build_object('name', 'Invierte la llama', 'challenge', 'Ora sinceramente por la persona que te molestó.')),
    ('PSALM_OF_HOPE', jsonb_build_object('name', 'Responde al susurro', 'challenge', 'Lee un salmo de esperanza y escribe una frase verdadera.')),
    ('RETURN_NEXT_MEAL', jsonb_build_object('name', 'Reinicio sin drama', 'challenge', 'Después de una decisión imperfecta, vuelve a la moderación en la siguiente comida.')),
    ('RETURN_TODAY', jsonb_build_object('name', 'Comienza de nuevo', 'challenge', 'Retoma hoy un buen hábito abandonado durante al menos cinco minutos.')),
    ('SCRIPTURE_BEFORE_SCREEN', jsonb_build_object('name', 'La Palabra antes que la pantalla', 'challenge', 'Lee el Evangelio del día antes de abrir las redes sociales.')),
    ('SMALL_COMMITMENT', jsonb_build_object('name', 'Cruza el umbral', 'challenge', 'Asume hoy un compromiso pequeño y reversible.')),
    ('SOCIAL_FAST', jsonb_build_object('name', 'Cierra los binoculares', 'challenge', 'Descansa durante 24 horas de la aplicación que provoca la comparación.')),
    ('SPEAK_GOOD', jsonb_build_object('name', 'Sustitúyelo con honor', 'challenge', 'Di algo bueno, sincero y concreto sobre esa persona.')),
    ('TEN_MINUTE_PAUSE', jsonb_build_object('name', 'Baja el puente levadizo', 'challenge', 'Espera 10 minutos antes de responder y vuelve a leer tu mensaje.')),
    ('TWENTY_MINUTE_TASK', jsonb_build_object('name', 'Carga de veinte minutos', 'challenge', 'Trabaja durante 20 minutos concentrados en la tarea que más has evitado.')),
    ('VERIFY_OR_SILENCE', jsonb_build_object('name', 'Cierra el cofre de rumores', 'challenge', 'No repitas la historia a menos que sea verdadera, necesaria y caritativa.')),
    ('WAIT_24_HOURS', jsonb_build_object('name', 'La demora del discernimiento', 'challenge', 'Espera 24 horas antes de realizar una compra no esencial.')),
    ('WATER_AND_WAIT', jsonb_build_object('name', 'La tregua de diez minutos', 'challenge', 'Bebe agua y espera 10 minutos antes de decidir si vas a comer.'))
  ) as source(code, value)
  where target.code = source.code;

  update app.examination_of_conscience_questions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('Have I denied or abandoned the Catholic faith (apostasy)?', jsonb_build_object('title','Fe','question','¿He negado o abandonado la fe católica (apostasía)?','description','La apostasía es el rechazo total de la fe cristiana (CIC 2089). Es materia grave porque rechaza la revelación de Dios y rompe la comunión con la Iglesia.','counsels',jsonb_build_array('Regresa mediante la Confesión y una profesión de fe.','Estudia las enseñanzas fundamentales que rechazaste.','Busca la orientación de un sacerdote o mentor.'),'prevention',jsonb_build_array('Lectura diaria de la Escritura (10–15 minutos)','Lectura semanal del Catecismo','Mantente unido a una comunidad parroquial'),'saints',jsonb_build_array('San Agustín','San John Henry Newman'))),
    ('Have I seriously doubted or rejected a doctrine of the Church (heresy)?', jsonb_build_object('title','Fe','question','¿He dudado seriamente o rechazado una doctrina de la Iglesia (herejía)?','description','La herejía es la negación obstinada, después del Bautismo, de una verdad que debe creerse con fe divina (CIC 2089).','counsels',jsonb_build_array('Aclara qué rechazaste y por qué.','Busca la verdad con humildad, no con orgullo.','Presenta tus dudas intelectuales a una persona fiel.'),'prevention',jsonb_build_array('Catequesis estructurada','Evita contenido contrario a la fe','Haz preguntas desde el principio'),'saints',jsonb_build_array('Santo Tomás de Aquino'))),
    ('Have I engaged in superstition, horoscopes, or occult practices?', jsonb_build_object('title','Fe','question','¿He participado en supersticiones, horóscopos o prácticas ocultistas?','description','Toda forma de adivinación y ocultismo rechaza la confianza en Dios (CIC 2116–2117).','counsels',jsonb_build_array('Renuncia a ello explícitamente en la oración.','Elimina los objetos o aplicaciones relacionados.','Confiésalo y sustitúyelo por la confianza en Dios.'),'prevention',jsonb_build_array('Reza «Jesús, confío en ti»','Evita contenido ocultista','Busca orientación en la Escritura'),'saints',jsonb_build_array('San Benito','San Cipriano'))),
    ('Have I fallen into despair, believing God cannot forgive me?', jsonb_build_object('title','Esperanza','question','¿He caído en la desesperación, creyendo que Dios no puede perdonarme?','description','La desesperación rechaza la misericordia y la salvación de Dios (CIC 2091).','counsels',jsonb_build_array('La misericordia de Dios es infinita.','Confiésate y vuelve a confiar en Él.'),'prevention',jsonb_build_array('Devoción a la Divina Misericordia','Evita aislarte'),'saints',jsonb_build_array('Santa Faustina'))),
    ('Have I presumed God''s mercy without repentance?', jsonb_build_object('title','Esperanza','question','¿He presumido de la misericordia de Dios sin arrepentirme?','description','La presunción espera el perdón sin conversión (CIC 2092).','counsels',jsonb_build_array('Arrepiéntete sinceramente.','No justifiques el pecado.'),'prevention',jsonb_build_array('Confesión frecuente','Examen diario'),'saints',jsonb_build_array('Santa Teresa de Lisieux'))),
    ('Have I missed Sunday Mass without serious reason?', jsonb_build_object('title','Amor a Dios','question','¿He faltado a la Misa dominical sin una razón seria?','description','Faltar deliberadamente a Misa es materia grave (CIC 2181).','counsels',jsonb_build_array('Haz de la Misa una prioridad.','Confiésalo si faltaste deliberadamente.'),'prevention',jsonb_build_array('Planifica con anticipación','Configura recordatorios'),'saints',jsonb_build_array('San Juan Pablo II'))),
    ('Have I neglected daily prayer?', jsonb_build_object('title','Vida de oración','question','¿He descuidado la oración diaria?','description','La oración es necesaria para la vida espiritual (CIC 2744).','counsels',jsonb_build_array('Comienza con 5–10 minutos diarios.'),'prevention',jsonb_build_array('Rutina de mañana y noche'),'saints',jsonb_build_array('Santa Teresa de Ávila'))),
    ('Have I engaged in fornication?', jsonb_build_object('title','Castidad','question','¿He cometido fornicación?','description','Las relaciones sexuales fuera del matrimonio son gravemente pecaminosas (CIC 2353).','counsels',jsonb_build_array('Termina las relaciones pecaminosas.','Busca acompañamiento.'),'prevention',jsonb_build_array('Evita situaciones privadas','Establece límites'),'saints',jsonb_build_array('Santa María Goretti'))),
    ('Have I viewed pornography?', jsonb_build_object('title','Castidad','question','¿He visto pornografía?','description','La pornografía viola la dignidad y la pureza (CIC 2354).','counsels',jsonb_build_array('Confiésalo de inmediato.','Instala bloqueadores.'),'prevention',jsonb_build_array('Evita los desencadenantes','Permanece en espacios públicos'),'saints',jsonb_build_array('San Agustín'))),
    ('Have I committed masturbation?', jsonb_build_object('title','Castidad','question','¿He cometido masturbación?','description','La masturbación es un uso desordenado de la sexualidad (CIC 2352).','counsels',jsonb_build_array('Confiésalo y busca disciplina.'),'prevention',jsonb_build_array('Duchas frías','Ejercicio','Evita la ociosidad'),'saints',jsonb_build_array('San Juan Bosco'))),
    ('Have I committed adultery?', jsonb_build_object('title','Castidad','question','¿He cometido adulterio?','description','El adulterio viola la alianza matrimonial (CIC 2380).','counsels',jsonb_build_array('Termina la relación de inmediato.','Busca la reconciliación.'),'prevention',jsonb_build_array('Evita vínculos emocionales fuera del matrimonio'),'saints',jsonb_build_array('San José'))),
    ('Have I been abusive toward my spouse or children?', jsonb_build_object('title','Amor al prójimo','question','¿He maltratado a mi cónyuge o a mis hijos?','description','El maltrato viola la dignidad y la caridad (CIC 2302).','counsels',jsonb_build_array('Busca ayuda de inmediato.','Arrepiéntete sinceramente.'),'prevention',jsonb_build_array('Manejo de la ira','Consejería'),'saints',jsonb_build_array('San Francisco de Sales'))),
    ('Have I failed to provide for my family?', jsonb_build_object('title','Justicia','question','¿He dejado de proveer lo necesario para mi familia?','description','Descuidar las responsabilidades familiares es injusto (CIC 2211).','counsels',jsonb_build_array('Asume seriamente tu responsabilidad.'),'prevention',jsonb_build_array('Elabora un presupuesto','Disciplina en el trabajo'),'saints',jsonb_build_array('San José'))),
    ('Have I disobeyed legitimate authority?', jsonb_build_object('title','Obediencia','question','¿He desobedecido a la autoridad legítima?','description','La obediencia religiosa imita a Cristo (CIC 915).','counsels',jsonb_build_array('Practica la humildad.'),'prevention',jsonb_build_array('Confía en tus superiores'),'saints',jsonb_build_array('San Ignacio'))),
    ('Have I violated my vow of chastity?', jsonb_build_object('title','Castidad','question','¿He violado mi voto de castidad?','description','La castidad consagrada es una dedicación total a Dios (CIC 2349).','counsels',jsonb_build_array('Vuelve de inmediato a la gracia.'),'prevention',jsonb_build_array('Custodia de la mirada','Disciplina en la oración'),'saints',jsonb_build_array('Santa Clara'))),
    ('Have I been attached to material goods?', jsonb_build_object('title','Pobreza','question','¿Me he apegado a los bienes materiales?','description','La pobreza llama al desapego (CIC 2544).','counsels',jsonb_build_array('Vive con sencillez.'),'prevention',jsonb_build_array('Minimalismo','Generosidad'),'saints',jsonb_build_array('San Francisco'))),
    ('Have I taken the Lord’s name in vain seriously or blasphemed?', jsonb_build_object('title','Reverencia a Dios','question','¿He tomado gravemente el nombre del Señor en vano o he blasfemado?','description','La blasfemia es hablar contra Dios con odio, reproche o desafío y es gravemente pecaminosa (CIC 2148). Viola la reverencia debida al nombre de Dios.','counsels',jsonb_build_array('Reconoce la gravedad de tus palabras.','Repara mediante actos de reverencia, como la oración o la adoración.'),'prevention',jsonb_build_array('Sustituye las malas palabras por oraciones breves','Evita ambientes donde se normaliza la blasfemia'),'saints',jsonb_build_array('San Benito'))),
    ('Have I committed serious lying or deception that harmed others?', jsonb_build_object('title','Verdad','question','¿He mentido o engañado gravemente, causando daño a otros?','description','Mentir es decir una falsedad con intención de engañar (CIC 2482). Las mentiras que causan un daño serio son graves.','counsels',jsonb_build_array('Repara el daño causado.','Confiésalo con claridad.'),'prevention',jsonb_build_array('Practica una honestidad radical','Haz una pausa antes de hablar'),'saints',jsonb_build_array('Santo Tomás Moro'))),
    ('Have I stolen something of significant value?', jsonb_build_object('title','Justicia','question','¿He robado algo de valor considerable?','description','El robo viola la justicia y exige restitución (CIC 2408–2412).','counsels',jsonb_build_array('Devuelve lo que tomaste.','Haz restitución.'),'prevention',jsonb_build_array('Respeta los bienes ajenos','No justifiques el robo'),'saints',jsonb_build_array('San Zaqueo'))),
    ('Have I hated someone or wished serious harm upon them?', jsonb_build_object('title','Caridad','question','¿He odiado a alguien o le he deseado un daño grave?','description','El odio al prójimo es contrario a la caridad y puede ser gravemente pecaminoso (CIC 2303).','counsels',jsonb_build_array('Ora por esa persona.','Elige perdonar.'),'prevention',jsonb_build_array('Practica la empatía','Ora diariamente por tus enemigos'),'saints',jsonb_build_array('San Esteban'))),
    ('Have I refused to forgive someone who seriously hurt me?', jsonb_build_object('title','Caridad','question','¿Me he negado a perdonar a alguien que me hirió gravemente?','description','Negarse a perdonar bloquea la misericordia de Dios (CIC 2840).','counsels',jsonb_build_array('Perdonar es una decisión.','Suelta el resentimiento.'),'prevention',jsonb_build_array('Oración diaria por la sanación','Practica la misericordia'),'saints',jsonb_build_array('Santa María Goretti'))),
    ('Have I abused alcohol to the point of drunkenness?', jsonb_build_object('title','Templanza','question','¿He abusado del alcohol hasta emborracharme?','description','La embriaguez perjudica la razón y la dignidad (CIC 2290).','counsels',jsonb_build_array('Busca acompañamiento.','Reduce o elimina su consumo.'),'prevention',jsonb_build_array('Evita ambientes de excesos','Conoce tus límites'),'saints',jsonb_build_array('Santa Mónica'))),
    ('Have I used drugs or substances that harm my body or mind?', jsonb_build_object('title','Templanza','question','¿He usado drogas o sustancias que dañan mi cuerpo o mi mente?','description','El consumo de drogas es una falta grave contra la salud y la vida (CIC 2291).','counsels',jsonb_build_array('Busca ayuda de inmediato.','Confiésalo sinceramente.'),'prevention',jsonb_build_array('Evita ambientes dañinos','Mantén un acompañamiento responsable'),'saints',jsonb_build_array('San Maximiliano Kolbe'))),
    ('Have I deliberately entertained lustful thoughts?', jsonb_build_object('title','Castidad','question','¿He consentido deliberadamente pensamientos lujuriosos?','description','La lujuria es el deseo desordenado del placer sexual (CIC 2351).','counsels',jsonb_build_array('Rechaza esos pensamientos de inmediato.','Dirige tu atención hacia otra cosa.'),'prevention',jsonb_build_array('Custodia de la mirada','Disciplina mental'),'saints',jsonb_build_array('San José'))),
    ('Have I placed myself in near occasions of sexual sin?', jsonb_build_object('title','Castidad','question','¿Me he puesto en ocasiones próximas de pecado sexual?','description','Entrar conscientemente en la tentación pone en riesgo de pecado grave (CIC 2119).','counsels',jsonb_build_array('Identifica los desencadenantes.','Elimínalos.'),'prevention',jsonb_build_array('Evita aislarte','Establece límites'),'saints',jsonb_build_array('San Antonio Abad'))),
    ('Have I seriously damaged someone’s reputation (calumny or detraction)?', jsonb_build_object('title','Amor al prójimo','question','¿He dañado gravemente la reputación de alguien mediante calumnia o detracción?','description','Revelar injustamente las faltas de otros les causa daño (CIC 2477).','counsels',jsonb_build_array('Repara el daño.','Di la verdad con caridad.'),'prevention',jsonb_build_array('Evita el chisme','Piensa antes de hablar'),'saints',jsonb_build_array('San Francisco de Sales'))),
    ('Have I cheated in school, work, or business?', jsonb_build_object('title','Justicia','question','¿He hecho trampa en la escuela, el trabajo o los negocios?','description','El fraude y las trampas violan la justicia (CIC 2409).','counsels',jsonb_build_array('Haz restitución.','Actúa con honestidad en adelante.'),'prevention',jsonb_build_array('Cultiva una mentalidad íntegra','Evita los atajos'),'saints',jsonb_build_array('San José'))),
    ('Have I publicly denied my faith out of fear or shame?', jsonb_build_object('title','Fe','question','¿He negado públicamente mi fe por miedo o vergüenza?','description','No dar testimonio de Cristo puede ser grave (CIC 1816).','counsels',jsonb_build_array('Arrepiéntete y mantente firme.','Fortalece tu valentía.'),'prevention',jsonb_build_array('Practica pequeños actos de testimonio','Permanece arraigado en la verdad'),'saints',jsonb_build_array('San Pedro'))),
    ('Have I acted out of pride, placing myself above God or others?', jsonb_build_object('title','Humildad','question','¿He actuado por orgullo, colocándome por encima de Dios o de los demás?','description','El orgullo es la raíz del pecado (CIC 1866).','counsels',jsonb_build_array('Practica la humildad.','Sirve a los demás.'),'prevention',jsonb_build_array('Reflexión diaria sobre la humildad','Obras de servicio'),'saints',jsonb_build_array('San Agustín'))),
    ('Have I neglected my responsibilities out of laziness?', jsonb_build_object('title','Pereza','question','¿He descuidado mis responsabilidades por pereza?','description','La pereza es negligencia espiritual y física (CIC 2733).','counsels',jsonb_build_array('Forma disciplina.','Comienza con algo pequeño.'),'prevention',jsonb_build_array('Horario estructurado','Acompañamiento responsable'),'saints',jsonb_build_array('San Benito'))),
    ('Have I ignored the needs of the poor or suffering?', jsonb_build_object('title','Caridad','question','¿He ignorado las necesidades de los pobres o de quienes sufren?','description','Descuidar la caridad es pecado (CIC 2447).','counsels',jsonb_build_array('Sé generoso.','Sirve activamente.'),'prevention',jsonb_build_array('Da con regularidad','Haz voluntariado'),'saints',jsonb_build_array('Santa Teresa de Calcuta'))),
    ('Have I wasted money irresponsibly or been overly materialistic?', jsonb_build_object('title','Justicia','question','¿He gastado dinero irresponsablemente o he sido demasiado materialista?','description','El apego a la riqueza aleja de Dios (CIC 2424).','counsels',jsonb_build_array('Simplifica tu vida.','Da prioridad a Dios.'),'prevention',jsonb_build_array('Administra sabiamente tu presupuesto','Practica el desapego'),'saints',jsonb_build_array('San Francisco'))),
    ('Have I been gluttonous or lacked self-control?', jsonb_build_object('title','Templanza','question','¿He caído en la gula o me ha faltado dominio propio?','description','La gula es un consumo desordenado (CIC 1866).','counsels',jsonb_build_array('Practica la moderación.'),'prevention',jsonb_build_array('Ayuno','Disciplina'),'saints',jsonb_build_array('Santo Tomás de Aquino'))),
    ('Have I judged others rashly without sufficient evidence?', jsonb_build_object('title','Amor al prójimo','question','¿He juzgado temerariamente a otros sin pruebas suficientes?','description','El juicio temerario viola la caridad (CIC 2478).','counsels',jsonb_build_array('Presume buenas intenciones.'),'prevention',jsonb_build_array('Haz una pausa antes de juzgar'),'saints',jsonb_build_array('San Ignacio'))),
    ('Have I placed relationships, career, or success above God?', jsonb_build_object('title','Fe','question','¿He puesto mis relaciones, mi carrera o el éxito por encima de Dios?','description','La idolatría coloca las cosas creadas por encima de Dios (CIC 2113).','counsels',jsonb_build_array('Ordena nuevamente tus prioridades.'),'prevention',jsonb_build_array('Oración diaria','Disciplina espiritual'),'saints',jsonb_build_array('San Francisco'))),
    ('Have I ignored God’s call in my life or failed to discern my vocation?', jsonb_build_object('title','Vida de oración','question','¿He ignorado la llamada de Dios en mi vida o dejado de discernir mi vocación?','description','Cada persona tiene una llamada de Dios (CIC 2232).','counsels',jsonb_build_array('Ora para recibir claridad.','Busca orientación.'),'prevention',jsonb_build_array('Dirección espiritual','Silencio y oración'),'saints',jsonb_build_array('San Juan Pablo II')))
  ) as source(question, value)
  where target.question = source.question;

  update app.examination_of_conscience_questions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('Have I engaged in emotional infidelity or an inappropriate attachment to someone other than my spouse?', jsonb_build_object('title','Fidelidad','question','¿He cometido una infidelidad emocional o formado un vínculo inapropiado con alguien que no es mi cónyuge?','description','Las relaciones emocionales impropias violan la exclusividad del amor matrimonial y pueden conducir al adulterio (CIC 2380–2381).','counsels',jsonb_build_array('Corta de inmediato todo contacto inapropiado.','Sé transparente con tu cónyuge.','Busca consejería matrimonial o dirección espiritual.'),'prevention',jsonb_build_array('Establece límites claros con personas del sexo opuesto','Comparte regularmente tus luchas con tu cónyuge','Evita mensajes privados con antiguas parejas'),'saints',jsonb_build_array('San José','Santa Mónica'))),
    ('Have I used artificial contraception to prevent pregnancy?', jsonb_build_object('title','Apertura a la vida','question','¿He usado anticonceptivos artificiales para impedir un embarazo?','description','La anticoncepción separa los significados unitivo y procreador del acto matrimonial y es gravemente desordenada (CIC 2370).','counsels',jsonb_build_array('Aprendan y practiquen la Planificación Familiar Natural.','Habla con tu cónyuge sobre la apertura a la vida.','Confiésate y busca orientación de un sacerdote fiel.'),'prevention',jsonb_build_array('Tomen juntos un curso de PFN','Lean Humanae Vitae','Oren juntos sobre la planificación familiar'),'saints',jsonb_build_array('Santos Luis y Celia Martin'))),
    ('Have I neglected my spouse emotionally, spiritually, or physically?', jsonb_build_object('title','Caridad','question','¿He descuidado emocional, espiritual o físicamente a mi cónyuge?','description','Los esposos están llamados a la entrega mutua; el descuido debilita la alianza matrimonial (CIC 1643).','counsels',jsonb_build_array('Reserva tiempo habitual para estar juntos sin distracciones.','Pregunta a tu cónyuge qué le hace sentirse amado.','Da prioridad a tu matrimonio sobre el trabajo y los pasatiempos.'),'prevention',jsonb_build_array('Una cita semanal','Conversaciones diarias para saber cómo están','Un retiro matrimonial anual'),'saints',jsonb_build_array('Santos Luis y Celia Martin'))),
    ('Have I failed to lead my family in faith, prayer, or moral formation?', jsonb_build_object('title','Liderazgo','question','¿He dejado de guiar a mi familia en la fe, la oración o la formación moral?','description','Los padres son los primeros educadores de sus hijos y deben guiarlos hacia Dios (CIC 2223–2226).','counsels',jsonb_build_array('Comienza la oración familiar, aunque sea breve.','Enseña la fe a tus hijos con el ejemplo.','Toma la iniciativa en vez de esperar a tu cónyuge.'),'prevention',jsonb_build_array('Rosario familiar u oración antes de dormir','Misa dominical como hábito familiar no negociable','Lean juntos una historia bíblica durante las comidas'),'saints',jsonb_build_array('San José','San Juan Crisóstomo'))),
    ('Have I verbally or emotionally abused my spouse or children?', jsonb_build_object('title','Caridad','question','¿He maltratado verbal o emocionalmente a mi cónyuge o a mis hijos?','description','El maltrato verbal y emocional viola la dignidad de la persona y destruye la confianza familiar (CIC 2302–2303).','counsels',jsonb_build_array('Pide perdón sinceramente y comprométete a cambiar.','Busca consejería profesional o ayuda para manejar la ira.','Pide perdón a tu familia.'),'prevention',jsonb_build_array('Aléjate cuando aumente la ira','Practica hablar con mansedumbre','Confesión y examen personal frecuentes'),'saints',jsonb_build_array('San Francisco de Sales'))),
    ('Have I failed to pray with or for my spouse and family?', jsonb_build_object('title','Vida de oración','question','¿He dejado de orar con mi cónyuge y mi familia o por ellos?','description','La iglesia doméstica se fortalece con la oración compartida; descuidarla debilita la vida espiritual familiar (CIC 2685).','counsels',jsonb_build_array('Comienza con una oración compartida al día.','Invita a tu cónyuge a orar contigo, aunque sea brevemente.','Ora cada día por sus intenciones.'),'prevention',jsonb_build_array('Fija una hora para la oración familiar','Recen juntos el Rosario cada semana','Asistan juntos a Misa como familia'),'saints',jsonb_build_array('Santos Luis y Celia Martin'))),
    ('Have I been financially irresponsible, putting my family at risk through reckless spending, gambling, or debt?', jsonb_build_object('title','Justicia','question','¿He sido irresponsable con el dinero, poniendo en riesgo a mi familia mediante gastos imprudentes, apuestas o deudas?','description','Los esposos tienen el deber de justicia de atender responsablemente las necesidades materiales de su familia (CIC 2409).','counsels',jsonb_build_array('Elaboren juntos un presupuesto familiar.','Confiesa a tu cónyuge las deudas o gastos ocultos.','Busca asesoría financiera si la necesitas.'),'prevention',jsonb_build_array('Revisión mensual del presupuesto con tu cónyuge','Evita compras impulsivas','Practica la generosidad dentro de tus posibilidades'),'saints',jsonb_build_array('San José'))),
    ('Have I refused to forgive my spouse or held grudges in our marriage?', jsonb_build_object('title','Misericordia','question','¿Me he negado a perdonar a mi cónyuge o he guardado rencor en nuestro matrimonio?','description','El perdón es esencial para el amor matrimonial; rechazarlo endurece el corazón y daña el vínculo (CIC 2843).','counsels',jsonb_build_array('Elige perdonar con la voluntad, aunque tus sentimientos se resistan.','Lleva las heridas no resueltas a la Confesión y la oración.','Busca terapia de pareja para las heridas profundas.'),'prevention',jsonb_build_array('Resuelvan diariamente los conflictos','Recen juntos el Padrenuestro meditando «perdona nuestras ofensas como también nosotros perdonamos»','Practica pequeños actos de bondad después de un desacuerdo'),'saints',jsonb_build_array('Santa Rita de Casia'))),
    ('Have I refused the marital debt or used my spouse for selfish sexual gratification?', jsonb_build_object('title','Castidad','question','¿He rechazado injustamente el deber conyugal o usado a mi cónyuge para una gratificación sexual egoísta?','description','Los esposos se deben entrega mutua; el egoísmo o la coacción en el acto matrimonial viola su significado (CIC 2362–2363).','counsels',jsonb_build_array('Habla de la intimidad con honestidad y caridad.','Pon las necesidades de tu cónyuge antes que las tuyas.','Busca orientación de un sacerdote fiel si es necesario.'),'prevention',jsonb_build_array('Lean juntos la Teología del Cuerpo','Comuniquen abiertamente sus expectativas','Oren por la pureza dentro del matrimonio'),'saints',jsonb_build_array('San Juan Pablo II'))),
    ('Have I pressured my spouse toward sterilization or abortion?', jsonb_build_object('title','Apertura a la vida','question','¿He presionado a mi cónyuge para que acepte la esterilización o el aborto?','description','La esterilización directa y el aborto son gravemente pecaminosos; rechazan el don de la vida de Dios (CIC 2271, 2399).','counsels',jsonb_build_array('Arrepiéntete y confiésate de inmediato.','Si hubo esterilización, busca orientación pastoral.','Acompaña a tu cónyuge en su sanación.'),'prevention',jsonb_build_array('Conozcan juntos la enseñanza de la Iglesia sobre la vida','Confíen en la providencia de Dios','Únanse a un grupo provida de apoyo'),'saints',jsonb_build_array('Santa Gianna Beretta Molla'))),
    ('Have I prioritized work, hobbies, or screens over quality time with my family?', jsonb_build_object('title','Templanza','question','¿He dado prioridad al trabajo, los pasatiempos o las pantallas sobre el tiempo de calidad con mi familia?','description','Descuidar a la familia por distracciones incumple el deber de amor hacia el cónyuge y los hijos (CIC 2211).','counsels',jsonb_build_array('Establece límites firmes para el horario de trabajo.','Guarda los dispositivos durante el tiempo familiar.','Está plenamente presente para tu cónyuge y tus hijos.'),'prevention',jsonb_build_array('Comidas familiares diarias sin dispositivos','Una actividad o salida familiar semanal','Limita las redes sociales a horarios definidos'),'saints',jsonb_build_array('San José'))),
    ('Have I lied to my spouse about serious matters or lived a double life?', jsonb_build_object('title','Verdad','question','¿He mentido a mi cónyuge sobre asuntos graves o llevado una doble vida?','description','La mentira destruye la confianza, fundamento del matrimonio; el engaño grave es gravemente pecaminoso (CIC 2482–2484).','counsels',jsonb_build_array('Di la verdad a tu cónyuge con humildad.','Acepta las consecuencias de tu deshonestidad.','Reconstruye la confianza con transparencia constante.'),'prevention',jsonb_build_array('Practica la honestidad radical, incluso en lo pequeño','Comparte abiertamente contraseñas e información financiera','Busca acompañamiento de un amigo o mentor de confianza'),'saints',jsonb_build_array('Santo Tomás Moro'))),
    ('Have I spoken badly about my spouse to others or publicly humiliated them?', jsonb_build_object('title','Caridad','question','¿He hablado mal de mi cónyuge o lo he humillado públicamente?','description','La detracción contra el propio cónyuge daña su reputación y viola la caridad matrimonial (CIC 2477).','counsels',jsonb_build_array('Pide perdón a tu cónyuge y a quienes te escucharon.','Habla bien de tu cónyuge en público.','Presenta tus quejas directamente a tu cónyuge.'),'prevention',jsonb_build_array('Elogia en público y corrige en privado','Desahógate solo con un director espiritual o consejero','Ora por tu cónyuge cuando estés frustrado'),'saints',jsonb_build_array('San Francisco de Sales'))),
    ('Have I failed to raise my children in the Catholic faith or neglected their sacramental preparation?', jsonb_build_object('title','Fe','question','¿He dejado de educar a mis hijos en la fe católica o descuidado su preparación sacramental?','description','En el Bautismo los padres prometen educar a sus hijos en la fe; descuidar este deber es una falta seria (CIC 2225–2226).','counsels',jsonb_build_array('Inscríbelos en formación religiosa.','Enséñales las oraciones básicas y el significado de los sacramentos.','Sé un ejemplo de fe que puedan seguir.'),'prevention',jsonb_build_array('Asistan juntos a Misa cada domingo','Ora diariamente con tus hijos','Hablen naturalmente de la fe en la vida diaria'),'saints',jsonb_build_array('Santos Luis y Celia Martin','Santa Mónica'))),
    ('Have I been impatient, harsh, or dismissive toward my children?', jsonb_build_object('title','Paciencia','question','¿He sido impaciente, duro o despectivo con mis hijos?','description','Los padres deben guiar a sus hijos con paciencia y amor, sin provocarlos a la ira (CIC 2223; Ef 6,4).','counsels',jsonb_build_array('Pide perdón a tus hijos cuando pierdas la paciencia.','Corrige con calma y razón, no con ira.','Dedica tiempo individual a cada hijo.'),'prevention',jsonb_build_array('Haz una pausa antes de reaccionar con frustración','Establece normas coherentes y justas','Ora diariamente por paciencia'),'saints',jsonb_build_array('San Juan Bosco'))),
    ('Have I refused to seek help for my marriage when it was struggling?', jsonb_build_object('title','Humildad','question','¿Me he negado a buscar ayuda cuando mi matrimonio atravesaba dificultades?','description','El orgullo puede impedir que los esposos busquen la ayuda necesaria y permitir que las heridas se profundicen (CIC 1608).','counsels',jsonb_build_array('Acude a un sacerdote, diácono o consejero matrimonial católico.','Participa en un programa o retiro matrimonial.','Sé honesto sobre el estado de tu matrimonio.'),'prevention',jsonb_build_array('Retiro o encuentro matrimonial anual','Conserva amistades con otros matrimonios fieles','Confesión y dirección espiritual frecuentes'),'saints',jsonb_build_array('Santa Rita de Casia'))),
    ('Have I viewed pornography or engaged in lustful fantasies about someone other than my spouse?', jsonb_build_object('title','Castidad','question','¿He visto pornografía o consentido fantasías lujuriosas sobre alguien que no es mi cónyuge?','description','La pornografía y las fantasías lujuriosas violan la fidelidad matrimonial y la dignidad humana (CIC 2354, 2528).','counsels',jsonb_build_array('Confiésalo de inmediato e instala filtros de contenido.','Habla con tu cónyuge si corresponde y busca acompañamiento.','Únete a un grupo o programa de recuperación.'),'prevention',jsonb_build_array('Instala software de acompañamiento en todos los dispositivos','Evita estar a solas con pantallas por la noche','Reza diariamente el Rosario por la pureza'),'saints',jsonb_build_array('San Agustín','San José')))
  ) as source(question, value)
  where target.question = source.question;

  update app.examination_of_conscience_questions as target
  set translations = jsonb_set(target.translations, '{es}', source.value, true)
  from (values
    ('Have I persistently refused to obey my legitimate superiors in matters of community life?', jsonb_build_object('title','Obediencia','question','¿Me he negado persistentemente a obedecer a mis superiores legítimos en asuntos de la vida comunitaria?','description','La obediencia religiosa participa de la obediencia de Cristo y es un voto hecho libremente a Dios (CIC 915, 2103).','counsels',jsonb_build_array('Examina la raíz de tu resistencia: orgullo, miedo o una preocupación legítima.','Habla abiertamente con tu superior sobre tus dificultades.','Vuelve a entregar tu voluntad a Dios mediante tu voto.'),'prevention',jsonb_build_array('Renovación diaria de los votos en la oración matutina','Dirección espiritual frecuente','Medita la obediencia de Cristo en Getsemaní'),'saints',jsonb_build_array('San Ignacio de Loyola','Santa Faustina'))),
    ('Have I entertained romantic or sexual fantasies, or formed an exclusive emotional attachment?', jsonb_build_object('title','Castidad','question','¿He consentido fantasías románticas o sexuales, o formado un vínculo emocional exclusivo?','description','La castidad consagrada exige un amor indiviso a Dios; los vínculos exclusivos debilitan este don (CIC 2349, 916).','counsels',jsonb_build_array('Presenta el vínculo de inmediato a tu director espiritual.','Establece límites firmes con la persona implicada.','Dirige tu afecto hacia Cristo mediante la oración.'),'prevention',jsonb_build_array('Custodia de la mirada y la imaginación','Evita encuentros privados que generen intimidad','Cultiva amistades sanas dentro de la comunidad'),'saints',jsonb_build_array('Santa Clara de Asís','Santa María Goretti'))),
    ('Have I secretly kept money, possessions, or privileges for myself against my community''s rule?', jsonb_build_object('title','Pobreza','question','¿He guardado en secreto dinero, posesiones o privilegios para mí contra la regla de mi comunidad?','description','El voto de pobreza llama al desapego de los bienes y a compartirlo todo en común (CIC 2544–2545).','counsels',jsonb_build_array('Entrega a tu superior los objetos o fondos ocultos.','Confiesa sinceramente tus apegos.','Abraza la sencillez como camino de libertad.'),'prevention',jsonb_build_array('Inventario frecuente de tus pertenencias','Pide permiso antes de adquirir algo','Medita la pobreza de Cristo en el pesebre y la cruz'),'saints',jsonb_build_array('San Francisco de Asís'))),
    ('Have I habitually skipped the Liturgy of the Hours, community prayer, or personal meditation?', jsonb_build_object('title','Vida de oración','question','¿He omitido habitualmente la Liturgia de las Horas, la oración comunitaria o la meditación personal?','description','La oración es el fundamento de la vida consagrada; descuidarla conduce a la sequedad espiritual y al debilitamiento de la vocación (CIC 2691, 2744).','counsels',jsonb_build_array('Retoma hoy mismo tu horario de oración.','Lleva tu sequedad a la dirección espiritual.','Si estás abrumado, comienza con cinco minutos de silencio.'),'prevention',jsonb_build_array('Horario fijo de oración con apoyo comunitario','Trata la oración como una cita sagrada','Varía las formas de oración para combatir la rutina'),'saints',jsonb_build_array('Santa Teresa de Ávila','San Juan de la Cruz'))),
    ('Have I caused scandal by living contrary to the vows I profess publicly?', jsonb_build_object('title','Verdad','question','¿He causado escándalo viviendo en contra de los votos que profeso públicamente?','description','El escándalo lleva a otros al pecado y es especialmente grave cuando lo causa quien enseña o representa la fe (CIC 2284–2285).','counsels',jsonb_build_array('Reconoce el daño causado por tu testimonio.','Confiésate y repara cuando sea posible.','Renueva tu compromiso con un testimonio auténtico.'),'prevention',jsonb_build_array('Vive consciente de que Dios ve tus acciones','Examen frecuente sobre tu testimonio público','Pide a un compañero de confianza comentarios sinceros'),'saints',jsonb_build_array('San Pedro','San Juan María Vianney'))),
    ('Have I acted out of pride in my ministry, seeking recognition or control?', jsonb_build_object('title','Humildad','question','¿He actuado con orgullo en mi ministerio, buscando reconocimiento o control?','description','El orgullo en el ministerio convierte el servicio en autopromoción y contradice el espíritu de Cristo servidor (CIC 1831, 2540).','counsels',jsonb_build_array('Entrega cada mañana tu ministerio a Dios.','Acepta tareas ocultas sin quejarte.','Celebra los dones ajenos sin envidia.'),'prevention',jsonb_build_array('Comienza cada tarea con una oración de entrega','Busca el último lugar en las reuniones','Ayuna de hablar de tus logros'),'saints',jsonb_build_array('Santa Teresa de Lisieux','San Vicente de Paúl'))),
    ('Have I been uncharitable, critical, or cold toward members of my religious community?', jsonb_build_object('title','Caridad','question','¿He sido poco caritativo, crítico o frío con los miembros de mi comunidad religiosa?','description','La vida comunitaria exige caridad paciente; la falta persistente de bondad hiere el Cuerpo de Cristo (CIC 1822, 2447).','counsels',jsonb_build_array('Pide perdón a quienes hayas herido.','Practica pequeños actos de bondad hacia la persona más difícil.','Examina si tus críticas proyectan tus propias faltas.'),'prevention',jsonb_build_array('Ora diariamente por cada miembro de la comunidad','Di de otros solo lo que dirías en su presencia','Practica el caminito de sacrificios pequeños y ocultos'),'saints',jsonb_build_array('Santa Teresa de Lisieux'))),
    ('Have I misused authority over those entrusted to my care?', jsonb_build_object('title','Justicia','question','¿He usado mal la autoridad sobre quienes me fueron confiados?','description','La autoridad en la vida religiosa debe servir, no dominar; abusar de ella viola gravemente la justicia (CIC 2235–2236).','counsels',jsonb_build_array('Examina si ejerces el poder para los demás o para ti.','Pide perdón a quienes hayas tratado mal.','Somete tu liderazgo a revisiones periódicas.'),'prevention',jsonb_build_array('Imita el liderazgo servidor de Cristo que lava los pies','Mantén canales abiertos para recibir comentarios','Lee regularmente sobre la espiritualidad del liderazgo'),'saints',jsonb_build_array('San Benito','San Gregorio Magno'))),
    ('Have I celebrated the Eucharist or sacraments routinely, without reverence or interior devotion?', jsonb_build_object('title','Amor a Dios','question','¿He celebrado rutinariamente la Eucaristía o los sacramentos sin reverencia ni devoción interior?','description','La Eucaristía exige participación interior; la irreverencia habitual disminuye su poder transformador (CIC 1387–1388).','counsels',jsonb_build_array('Prepárate para la Misa con oración silenciosa.','Renueva tu conciencia de la Presencia Real de Cristo.','Da gracias después de recibir la Comunión.'),'prevention',jsonb_build_array('Llega diez minutos antes para guardar silencio','Lee previamente las lecturas del día','Haz un retiro mensual centrado en la Eucaristía'),'saints',jsonb_build_array('San Pedro Julián Eymard','San Pío de Pietrelcina'))),
    ('Have I murmured against or undermined my superior''s decisions behind their back?', jsonb_build_object('title','Obediencia','question','¿He murmurado contra las decisiones de mi superior o las he socavado a sus espaldas?','description','La murmuración y el chisme contra la autoridad destruyen la confianza comunitaria y violan el espíritu de obediencia (CIC 2477, 2103).','counsels',jsonb_build_array('Presenta tus desacuerdos directamente a tu superior.','Deja de participar en círculos de queja.','Ora diariamente por tus superiores.'),'prevention',jsonb_build_array('Practica la comunicación directa','Reza un Avemaría cuando sientas la tentación de quejarte','Escribe en privado tus frustraciones antes de hablar'),'saints',jsonb_build_array('San Ignacio de Loyola'))),
    ('Have I lived extravagantly or sought unnecessary comforts contrary to my vow?', jsonb_build_object('title','Pobreza','question','¿He vivido con lujo o buscado comodidades innecesarias contrarias a mi voto?','description','La pobreza religiosa testimonia el desapego de los bienes mundanos; la indulgencia contradice este testimonio (CIC 2544–2546).','counsels',jsonb_build_array('Simplifica tu espacio y tus hábitos.','Devuelve a la comunidad los objetos innecesarios.','Acepta la incomodidad como participación en la pobreza de Cristo.'),'prevention',jsonb_build_array('Revisión periódica de la sencillez de tu habitación','Pregunta antes de comprar si lo necesitas o solo lo deseas','Ofrécete para las tareas menos cómodas'),'saints',jsonb_build_array('San Francisco de Asís','Beato Carlos de Foucauld'))),
    ('Have I been hypocritical — presenting a holy image externally while living differently in private?', jsonb_build_object('title','Verdad','question','¿He sido hipócrita, mostrando exteriormente una imagen santa mientras vivo de otra manera en privado?','description','La hipocresía es una forma de mentira que daña gravemente la propia alma y la confianza de otros en la fe (CIC 2468, 2505).','counsels',jsonb_build_array('Sé sincero sobre tu vida interior en la dirección espiritual.','Haz que tu vida privada coincida con tu testimonio público.','Confiesa también los patrones de duplicidad.'),'prevention',jsonb_build_array('Examen diario con total sinceridad','Cultiva un confidente de confianza que conozca tu realidad','Reza para ser la misma persona en público y en privado'),'saints',jsonb_build_array('San Juan María Vianney'))),
    ('Have I been intemperate with food, drink, or digital media in a way that harms my spiritual life?', jsonb_build_object('title','Templanza','question','¿He sido intemperante con la comida, la bebida o los medios digitales de modo que dañe mi vida espiritual?','description','La templanza modera los deseos y es esencial para el testimonio religioso; el exceso embota los sentidos espirituales (CIC 1809, 2290).','counsels',jsonb_build_array('Ayuna o abstente como acto concreto de renuncia.','Establece límites firmes al consumo de medios y entretenimiento.','Sustituye los hábitos indulgentes por oración o servicio.'),'prevention',jsonb_build_array('Cumple fielmente los ayunos de tu comunidad','No uses pantallas después de la oración nocturna','Añade un ayuno semanal al mínimo requerido'),'saints',jsonb_build_array('San Benito','San Juan Bautista'))),
    ('Have I gossiped about or detracted from the reputation of fellow religious?', jsonb_build_object('title','Caridad','question','¿He chismeado o dañado la reputación de otros religiosos?','description','La detracción daña injustamente la reputación ajena y hiere la vida comunitaria (CIC 2477, 2479).','counsels',jsonb_build_array('Pide perdón a quienes hayas perjudicado.','Repara el daño hablando bien ante las mismas personas.','Comprométete a decir solo lo verdadero, necesario y amable.'),'prevention',jsonb_build_array('Aplica las tres puertas: ¿es verdad, necesario y amable?','Retírate de conversaciones que se vuelvan chisme','Ora por quienes te sientas tentado a criticar'),'saints',jsonb_build_array('San Francisco de Sales','San Felipe Neri'))),
    ('Have I become complacent in my vocation, going through the motions without love?', jsonb_build_object('title','Celo','question','¿Me he vuelto indiferente en mi vocación, cumpliendo por rutina y sin amor?','description','La tibieza en la vida consagrada es acedia espiritual: un cansancio que rechaza la alegría de Dios (CIC 2094, 2733).','counsels',jsonb_build_array('Renueva tus votos consciente y devotamente.','Pide a Dios que reavive tu primer amor.','Busca un nuevo apostolado que renueve tu celo.'),'prevention',jsonb_build_array('Retiro anual centrado en tu historia vocacional','Sirve periódicamente en una nueva función','Lee vidas de santos que compartieron tu carisma'),'saints',jsonb_build_array('Santa Teresa de Ávila','San Ignacio de Loyola'))),
    ('Have I used community resources selfishly or wasted what belongs to the community?', jsonb_build_object('title','Justicia','question','¿He usado egoístamente los recursos de la comunidad o desperdiciado lo que le pertenece?','description','Los bienes comunitarios se administran en confianza; desperdiciarlos viola la justicia y el bien común (CIC 2404–2405).','counsels',jsonb_build_array('Devuelve o reemplaza lo que utilizaste mal.','Habla abiertamente del uso de recursos en la comunidad.','Practica la gratitud por lo que recibes.'),'prevention',jsonb_build_array('Trata la propiedad comunitaria como algo sagrado','Pide permiso antes de usar bienes comunes para necesidades personales','Ofrécete para tareas de administración'),'saints',jsonb_build_array('San Basilio Magno'))),
    ('Have I allowed intellectual pride to distance me from simple, childlike faith?', jsonb_build_object('title','Fe','question','¿He permitido que el orgullo intelectual me aleje de una fe sencilla y confiada?','description','El orgullo intelectual puede sustituir la confianza en Dios por la confianza en el propio entendimiento (CIC 2088, 1831).','counsels',jsonb_build_array('Acércate a la Escritura y a la oración con corazón de principiante.','Somete tu inteligencia a la fe de la Iglesia.','Busca sabiduría, no solo conocimiento.'),'prevention',jsonb_build_array('Reza con frecuencia las Letanías de la Humildad','Estudia por obediencia, no solo por interés personal','Convive con personas de fe sencilla'),'saints',jsonb_build_array('Santo Tomás de Aquino','Santa Teresa de Lisieux')))
  ) as source(question, value)
  where target.question = source.question;
end
$$;

revoke all on function platform.apply_spanish_catalog_translations() from public, anon, authenticated;
grant execute on function platform.apply_spanish_catalog_translations() to service_role;

select platform.apply_spanish_catalog_translations();
